/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in overlord_monitor.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUDIT_LOG_IDX_AUDIT_ACTOR = Internal.createIndex(DSL.name("idx_audit_actor"), AuditLog.AUDIT_LOG, new OrderField[] { AuditLog.AUDIT_LOG.ACTOR_USERNAME, AuditLog.AUDIT_LOG.OCCURRED_AT }, false);
    public static final Index AUDIT_LOG_IDX_AUDIT_OCCURRED = Internal.createIndex(DSL.name("idx_audit_occurred"), AuditLog.AUDIT_LOG, new OrderField[] { AuditLog.AUDIT_LOG.OCCURRED_AT }, false);
    public static final Index AUDIT_LOG_IDX_AUDIT_TYPE = Internal.createIndex(DSL.name("idx_audit_type"), AuditLog.AUDIT_LOG, new OrderField[] { AuditLog.AUDIT_LOG.EVENT_TYPE, AuditLog.AUDIT_LOG.OCCURRED_AT }, false);
}
