/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUser;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUserMandant;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSollaenge;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSpalte;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollup;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.ProcessCatalog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.RollupLauf;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.AppUserMandantRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.AppUserRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.AuditLogRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.BamSollaengeRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.BamSpalteRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.MessageRollupRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.ProcessCatalogRecord;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.RollupLaufRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * overlord_monitor.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUserRecord> KEY_APP_USER_PRIMARY = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("KEY_app_user_PRIMARY"), new TableField[] { AppUser.APP_USER.ID }, true);
    public static final UniqueKey<AppUserRecord> KEY_APP_USER_UQ_APP_USER_USERNAME = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("KEY_app_user_uq_app_user_username"), new TableField[] { AppUser.APP_USER.USERNAME }, true);
    public static final UniqueKey<AppUserMandantRecord> KEY_APP_USER_MANDANT_PRIMARY = Internal.createUniqueKey(AppUserMandant.APP_USER_MANDANT, DSL.name("KEY_app_user_mandant_PRIMARY"), new TableField[] { AppUserMandant.APP_USER_MANDANT.USER_ID, AppUserMandant.APP_USER_MANDANT.MANDANT_ID }, true);
    public static final UniqueKey<AuditLogRecord> KEY_AUDIT_LOG_PRIMARY = Internal.createUniqueKey(AuditLog.AUDIT_LOG, DSL.name("KEY_audit_log_PRIMARY"), new TableField[] { AuditLog.AUDIT_LOG.ID }, true);
    public static final UniqueKey<BamSollaengeRecord> KEY_BAM_SOLLAENGE_PRIMARY = Internal.createUniqueKey(BamSollaenge.BAM_SOLLAENGE, DSL.name("KEY_bam_sollaenge_PRIMARY"), new TableField[] { BamSollaenge.BAM_SOLLAENGE.MANDANT_ID, BamSollaenge.BAM_SOLLAENGE.MESSAGE_BAM_TYPE }, true);
    public static final UniqueKey<BamSpalteRecord> KEY_BAM_SPALTE_PRIMARY = Internal.createUniqueKey(BamSpalte.BAM_SPALTE, DSL.name("KEY_bam_spalte_PRIMARY"), new TableField[] { BamSpalte.BAM_SPALTE.MANDANT_ID, BamSpalte.BAM_SPALTE.POSITION }, true);
    public static final UniqueKey<MessageRollupRecord> KEY_MESSAGE_ROLLUP_PRIMARY = Internal.createUniqueKey(MessageRollup.MESSAGE_ROLLUP, DSL.name("KEY_message_rollup_PRIMARY"), new TableField[] { MessageRollup.MESSAGE_ROLLUP.STUNDE, MessageRollup.MESSAGE_ROLLUP.PROCESS_ID, MessageRollup.MESSAGE_ROLLUP.MESSAGE_STATUS }, true);
    public static final UniqueKey<ProcessCatalogRecord> KEY_PROCESS_CATALOG_PRIMARY = Internal.createUniqueKey(ProcessCatalog.PROCESS_CATALOG, DSL.name("KEY_process_catalog_PRIMARY"), new TableField[] { ProcessCatalog.PROCESS_CATALOG.PROCESS_ID }, true);
    public static final UniqueKey<RollupLaufRecord> KEY_ROLLUP_LAUF_PRIMARY = Internal.createUniqueKey(RollupLauf.ROLLUP_LAUF, DSL.name("KEY_rollup_lauf_PRIMARY"), new TableField[] { RollupLauf.ROLLUP_LAUF.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppUserMandantRecord, AppUserRecord> FK_APP_USER_MANDANT_USER = Internal.createForeignKey(AppUserMandant.APP_USER_MANDANT, DSL.name("fk_app_user_mandant_user"), new TableField[] { AppUserMandant.APP_USER_MANDANT.USER_ID }, Keys.KEY_APP_USER_PRIMARY, new TableField[] { AppUser.APP_USER.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
}
