/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUser;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUserMandant;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSollaenge;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSpalte;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollup;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollupTag;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.ProcessCatalog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.RollupLauf;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OverlordMonitor extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor</code>
     */
    public static final OverlordMonitor OVERLORD_MONITOR = new OverlordMonitor();

    /**
     * The table <code>overlord_monitor.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>overlord_monitor.app_user_mandant</code>.
     */
    public final AppUserMandant APP_USER_MANDANT = AppUserMandant.APP_USER_MANDANT;

    /**
     * The table <code>overlord_monitor.audit_log</code>.
     */
    public final AuditLog AUDIT_LOG = AuditLog.AUDIT_LOG;

    /**
     * The table <code>overlord_monitor.bam_sollaenge</code>.
     */
    public final BamSollaenge BAM_SOLLAENGE = BamSollaenge.BAM_SOLLAENGE;

    /**
     * The table <code>overlord_monitor.bam_spalte</code>.
     */
    public final BamSpalte BAM_SPALTE = BamSpalte.BAM_SPALTE;

    /**
     * The table <code>overlord_monitor.message_rollup</code>.
     */
    public final MessageRollup MESSAGE_ROLLUP = MessageRollup.MESSAGE_ROLLUP;

    /**
     * The table <code>overlord_monitor.message_rollup_tag</code>.
     */
    public final MessageRollupTag MESSAGE_ROLLUP_TAG = MessageRollupTag.MESSAGE_ROLLUP_TAG;

    /**
     * The table <code>overlord_monitor.process_catalog</code>.
     */
    public final ProcessCatalog PROCESS_CATALOG = ProcessCatalog.PROCESS_CATALOG;

    /**
     * The table <code>overlord_monitor.rollup_lauf</code>.
     */
    public final RollupLauf ROLLUP_LAUF = RollupLauf.ROLLUP_LAUF;

    /**
     * No further instances allowed
     */
    private OverlordMonitor() {
        super(DSL.name("overlord_monitor"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppUser.APP_USER,
            AppUserMandant.APP_USER_MANDANT,
            AuditLog.AUDIT_LOG,
            BamSollaenge.BAM_SOLLAENGE,
            BamSpalte.BAM_SPALTE,
            MessageRollup.MESSAGE_ROLLUP,
            MessageRollupTag.MESSAGE_ROLLUP_TAG,
            ProcessCatalog.PROCESS_CATALOG,
            RollupLauf.ROLLUP_LAUF
        );
    }
}
