/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OverlordMonitor extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor</code>
     */
    public static final OverlordMonitor OVERLORD_MONITOR = new OverlordMonitor();

    /**
     * The table <code>overlord_monitor.audit_log</code>.
     */
    public final AuditLog AUDIT_LOG = AuditLog.AUDIT_LOG;

    /**
     * No further instances allowed
     */
    private OverlordMonitor() {
        super(DSL.name("overlord_monitor"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuditLog.AUDIT_LOG
        );
    }
}
