/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUser;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUserMandant;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSpalte;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OverlordMonitor extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor</code>
     */
    public static final OverlordMonitor OVERLORD_MONITOR = new OverlordMonitor();

    /**
     * The table <code>overlord_monitor.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>overlord_monitor.app_user_mandant</code>.
     */
    public final AppUserMandant APP_USER_MANDANT = AppUserMandant.APP_USER_MANDANT;

    /**
     * The table <code>overlord_monitor.audit_log</code>.
     */
    public final AuditLog AUDIT_LOG = AuditLog.AUDIT_LOG;

    /**
     * The table <code>overlord_monitor.bam_spalte</code>.
     */
    public final BamSpalte BAM_SPALTE = BamSpalte.BAM_SPALTE;

    /**
     * No further instances allowed
     */
    private OverlordMonitor() {
        super(DSL.name("overlord_monitor"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppUser.APP_USER,
            AppUserMandant.APP_USER_MANDANT,
            AuditLog.AUDIT_LOG,
            BamSpalte.BAM_SPALTE
        );
    }
}
