/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUser;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUserMandant;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSollaenge;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSpalte;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollup;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollupMonat;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollupTag;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.ProcessCatalog;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.RollupLauf;


/**
 * Convenience access to all tables in overlord_monitor.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>overlord_monitor.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>overlord_monitor.app_user_mandant</code>.
     */
    public static final AppUserMandant APP_USER_MANDANT = AppUserMandant.APP_USER_MANDANT;

    /**
     * The table <code>overlord_monitor.audit_log</code>.
     */
    public static final AuditLog AUDIT_LOG = AuditLog.AUDIT_LOG;

    /**
     * The table <code>overlord_monitor.bam_sollaenge</code>.
     */
    public static final BamSollaenge BAM_SOLLAENGE = BamSollaenge.BAM_SOLLAENGE;

    /**
     * The table <code>overlord_monitor.bam_spalte</code>.
     */
    public static final BamSpalte BAM_SPALTE = BamSpalte.BAM_SPALTE;

    /**
     * The table <code>overlord_monitor.message_rollup</code>.
     */
    public static final MessageRollup MESSAGE_ROLLUP = MessageRollup.MESSAGE_ROLLUP;

    /**
     * The table <code>overlord_monitor.message_rollup_monat</code>.
     */
    public static final MessageRollupMonat MESSAGE_ROLLUP_MONAT = MessageRollupMonat.MESSAGE_ROLLUP_MONAT;

    /**
     * The table <code>overlord_monitor.message_rollup_tag</code>.
     */
    public static final MessageRollupTag MESSAGE_ROLLUP_TAG = MessageRollupTag.MESSAGE_ROLLUP_TAG;

    /**
     * The table <code>overlord_monitor.process_catalog</code>.
     */
    public static final ProcessCatalog PROCESS_CATALOG = ProcessCatalog.PROCESS_CATALOG;

    /**
     * The table <code>overlord_monitor.rollup_lauf</code>.
     */
    public static final RollupLauf ROLLUP_LAUF = RollupLauf.ROLLUP_LAUF;
}
