/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;


/**
 * Convenience access to all tables in overlord_monitor.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>overlord_monitor.audit_log</code>.
     */
    public static final AuditLog AUDIT_LOG = AuditLog.AUDIT_LOG;
}
