-- Messung M80 — Was kostet die Pflegeliste des Prozess-Katalogs?
-- Auftrag:  "Schritt 9b Backend — Prozess-Katalog", Aufgabe 6 (Leistungsregel 7)
-- Frage:    L12 hat den GlassfishDB-Teil der Pflegeliste mit 4,2 ms gemessen, aber NICHT
--           den Join auf overlord_monitor.process_catalog — die Tabelle existierte nicht.
--           Was kostet der Join, jetzt wo sie existiert und gefuellt ist?
-- Ergebnis: docs/messungen-schritt9.md, Abschnitt M80
--
-- Ausschliesslich SELECT / SET / EXPLAIN / SHOW. (Regel S1)
--
-- G1: In dieser Datei steht kein Partnername, keine ProjectID und keine ProcessID.
-- Der Projektbezug fuer die Massenzuordnung wird in der Sitzung selbst
-- deterministisch hergeleitet (groesstes Projekt des Mandanten, bei Gleichstand
-- das alphabetisch erste) und steht als Sitzungsvariable in den Abfragen.
--
-- L7/L15: Gefahren gegen ZWEI Mandanten — NEXANS (733 Prozesse, groesster) und
-- SUTTONS (17, klein). Identische Abfragen sind in diesem Projekt schon um
-- Faktor 1.000 auseinandergelaufen; die Einstiegstabelle wird deshalb am EXPLAIN
-- abgelesen und nicht angenommen. Kein STRAIGHT_JOIN (M42).
--
-- Der gemessene Text ist aus dem Repository gegen eine jOOQ-Attrappe GERENDERT
-- (StatementType.STATIC_STATEMENT) und unterscheidet sich vom ausgelieferten nur
-- dort, wo eine Sitzungsvariable an die Stelle eines Literals tritt.

SELECT @@global.read_only AS read_only, VERSION() AS version, NOW() AS serverzeit,
       @@div_precision_increment AS dpi, @@session.sql_mode AS sql_mode;
SELECT USER() AS benutzer, CURRENT_USER() AS aufgeloest;
SET SESSION max_statement_time = 60;
SET profiling = 1;
SET profiling_history_size = 100;

-- ═══ Vorbedingung — traegt der Katalog ueberhaupt Zeilen? ═══════════════════
SELECT 'V0 Katalogbestand' AS marke;
SELECT COUNT(*) AS katalogzeilen,
       SUM(pflegestatus = 'OFFEN')     AS offen,
       SUM(pflegestatus = 'GEPFLEGT')  AS gepflegt,
       SUM(partner IS NOT NULL)        AS mit_partner,
       SUM(richtung IS NOT NULL)       AS mit_richtung
FROM overlord_monitor.process_catalog;

SELECT COUNT(*) AS zeilen_nexans
FROM overlord_monitor.process_catalog c
JOIN GlassfishDB.Process p ON p.ProcessID = c.process_id
JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID
WHERE pm.MandantID = 'NEXANS';

-- ═══ M80-1 — Pflegeliste, EXPLAIN je Mandant ═══════════════════════════════
SELECT 'M80-1 EXPLAIN NEXANS' AS marke;
EXPLAIN
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;

SELECT 'M80-1 EXPLAIN SUTTONS' AS marke;
EXPLAIN
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;

-- ═══ M80-1 — Pflegeliste, Laufzeit: ein Aufwaermlauf, dann fuenf ═══════════
SELECT 'M80-1 LAUFZEIT NEXANS (1 aufwaermen + 5)' AS marke;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;

SELECT 'M80-1 LAUFZEIT SUTTONS (1 aufwaermen + 5)' AS marke;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;

-- ═══ M80-2 — Gegenprobe: dieselbe Abfrage OHNE den Katalog-Join ═════════════
-- Das ist genau die Fassung, die L12 am 06.08.2026 mit 4,2 ms gemessen hat.
-- Die Differenz zu M80-1 ist der Preis des Joins und nichts sonst.
SELECT 'M80-2 OHNE KATALOG-JOIN, NEXANS (1 aufwaermen + 3)' AS marke;
SELECT p.ProcessID, p.ProcessName, pr.ProjectName FROM GlassfishDB.Process p JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID LEFT JOIN GlassfishDB.Project pr ON pr.ProjectID = p.ProjectID WHERE pm.MandantID = 'NEXANS' ORDER BY pr.ProjectName, p.ProcessName;
SELECT p.ProcessID, p.ProcessName, pr.ProjectName FROM GlassfishDB.Process p JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID LEFT JOIN GlassfishDB.Project pr ON pr.ProjectID = p.ProjectID WHERE pm.MandantID = 'NEXANS' ORDER BY pr.ProjectName, p.ProcessName;
SELECT p.ProcessID, p.ProcessName, pr.ProjectName FROM GlassfishDB.Process p JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID LEFT JOIN GlassfishDB.Project pr ON pr.ProjectID = p.ProjectID WHERE pm.MandantID = 'NEXANS' ORDER BY pr.ProjectName, p.ProcessName;
SELECT p.ProcessID, p.ProcessName, pr.ProjectName FROM GlassfishDB.Process p JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID LEFT JOIN GlassfishDB.Project pr ON pr.ProjectID = p.ProjectID WHERE pm.MandantID = 'NEXANS' ORDER BY pr.ProjectName, p.ProcessName;

-- ═══ M80-3 — Der Filter "nur offene" ═══════════════════════════════════════
SELECT 'M80-3 EXPLAIN nurOffene NEXANS' AS marke;
EXPLAIN
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and (`overlord_monitor`.`process_catalog`.`pflegestatus` is null or `overlord_monitor`.`process_catalog`.`pflegestatus` <> 'GEPFLEGT')) order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;

SELECT 'M80-3 LAUFZEIT nurOffene NEXANS (1 aufwaermen + 3)' AS marke;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and (`overlord_monitor`.`process_catalog`.`pflegestatus` is null or `overlord_monitor`.`process_catalog`.`pflegestatus` <> 'GEPFLEGT')) order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and (`overlord_monitor`.`process_catalog`.`pflegestatus` is null or `overlord_monitor`.`process_catalog`.`pflegestatus` <> 'GEPFLEGT')) order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and (`overlord_monitor`.`process_catalog`.`pflegestatus` is null or `overlord_monitor`.`process_catalog`.`pflegestatus` <> 'GEPFLEGT')) order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;
select `GlassfishDB`.`Process`.`ProcessID`, `GlassfishDB`.`Process`.`ProjectID`, `GlassfishDB`.`Project`.`ProjectName`, `GlassfishDB`.`Process`.`ProcessName`, `overlord_monitor`.`process_catalog`.`partner`, `overlord_monitor`.`process_catalog`.`richtung`, `overlord_monitor`.`process_catalog`.`pflegestatus`, `overlord_monitor`.`process_catalog`.`vorschlag_herkunft` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `GlassfishDB`.`Project` on `GlassfishDB`.`Project`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and (`overlord_monitor`.`process_catalog`.`pflegestatus` is null or `overlord_monitor`.`process_catalog`.`pflegestatus` <> 'GEPFLEGT')) order by `GlassfishDB`.`Project`.`ProjectName` asc, `GlassfishDB`.`Process`.`ProcessName` asc;

-- ═══ M80-4 — Die abgeleitete Partnerliste ══════════════════════════════════
SELECT 'M80-4 EXPLAIN Partnerliste NEXANS' AS marke;
EXPLAIN
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;

SELECT 'M80-4 LAUFZEIT Partnerliste NEXANS und SUTTONS (je 1 aufwaermen + 3)' AS marke;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;
select distinct `overlord_monitor`.`process_catalog`.`partner` from `overlord_monitor`.`process_catalog` join `GlassfishDB`.`Process` on `GlassfishDB`.`Process`.`ProcessID` = `overlord_monitor`.`process_catalog`.`process_id` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS' and `overlord_monitor`.`process_catalog`.`partner` is not null and `overlord_monitor`.`process_catalog`.`partner` <> '') order by `overlord_monitor`.`process_catalog`.`partner` asc;

-- ═══ M80-5 — Das Statement, das Vorschau und Ausfuehrung teilen ═════════════
-- Das Projekt wird hier hergeleitet und nicht eingetragen (G1): das groesste
-- Projekt von VOTG, laut M76 mit 226 Prozessen das groesste des Bestands.
SELECT 'M80-5 groesstes Projekt herleiten' AS marke;
SELECT p.ProjectID INTO @projekt
FROM GlassfishDB.Process p
JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID
WHERE pm.MandantID = 'VOTG'
GROUP BY p.ProjectID
ORDER BY COUNT(*) DESC, p.ProjectID ASC
LIMIT 1;
SELECT COUNT(*) AS prozesse_im_groessten_projekt
FROM GlassfishDB.Process p
JOIN GlassfishDB.ProjectMandant pm ON pm.ProjectID = p.ProjectID
WHERE pm.MandantID = 'VOTG' AND p.ProjectID = @projekt;

SELECT 'M80-5 EXPLAIN Projektbestand' AS marke;
EXPLAIN
select `GlassfishDB`.`Process`.`ProcessID`, `overlord_monitor`.`process_catalog`.`pflegestatus` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG' and `GlassfishDB`.`Process`.`ProjectID` = @projekt);

SELECT 'M80-5 LAUFZEIT Projektbestand (1 aufwaermen + 3)' AS marke;
select `GlassfishDB`.`Process`.`ProcessID`, `overlord_monitor`.`process_catalog`.`pflegestatus` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG' and `GlassfishDB`.`Process`.`ProjectID` = @projekt);
select `GlassfishDB`.`Process`.`ProcessID`, `overlord_monitor`.`process_catalog`.`pflegestatus` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG' and `GlassfishDB`.`Process`.`ProjectID` = @projekt);
select `GlassfishDB`.`Process`.`ProcessID`, `overlord_monitor`.`process_catalog`.`pflegestatus` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG' and `GlassfishDB`.`Process`.`ProjectID` = @projekt);
select `GlassfishDB`.`Process`.`ProcessID`, `overlord_monitor`.`process_catalog`.`pflegestatus` from `GlassfishDB`.`Process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `GlassfishDB`.`Process`.`ProjectID` left outer join `overlord_monitor`.`process_catalog` on `overlord_monitor`.`process_catalog`.`process_id` = `GlassfishDB`.`Process`.`ProcessID` where (`GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG' and `GlassfishDB`.`Process`.`ProjectID` = @projekt);

-- ═══ Laufzeiten und Abschluss ══════════════════════════════════════════════
SELECT 'PROFILES' AS marke;
SHOW PROFILES;
SELECT @@global.read_only AS read_only_ende, NOW() AS serverzeit_ende;
