-- M82 — Was kostet die letzte Anmeldung je Nutzer? (Leistungsregel 7, Schritt 9a, E17)
--
-- Der Text ist GERENDERT aus AppUserRepository.findeAlleKonten (jOOQ-Attrappe mit
-- StatementType.STATIC_STATEMENT), nicht nachgebaut. Er unterscheidet sich vom
-- ausgelieferten nur darin, dass hier keine Bindeplaetze stehen — es gibt keine.
--
-- G1: In dieser Datei steht kein Benutzername und kein Passwort. Die Ausgabe der
-- Hauptabfrage wird nicht mitgeschrieben, nur ihr Plan und ihre Laufzeit.

select now() as serverzeit, @@global.read_only as read_only, version() as version,
       @@div_precision_increment as div_precision_increment, current_user() as benutzer;

select count(*) as audit_log_zeilen from audit_log;
select count(*) as anmeldungen from audit_log where event_type = 'ANMELDUNG_ERFOLG';
select count(*) as konten from app_user;

-- ── Der Plan ────────────────────────────────────────────────────────────────
explain select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;

-- Nur die abgeleitete Tabelle, damit sichtbar ist, was die Aggregation allein kostet.
explain select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`;

-- Der Vorschlag, NICHT angelegt: was ein Index (event_type, actor_user_id, occurred_at) brächte.
explain select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) from `overlord_monitor`.`audit_log` use index (idx_audit_type) where `overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' group by `overlord_monitor`.`audit_log`.`actor_user_id`;

-- ── Laufzeit: ein Aufwaermlauf, danach fuenf ────────────────────────────────
set profiling = 1;
set profiling_history_size = 100;
select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;
select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;
select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;
select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;
select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;
select `overlord_monitor`.`app_user`.`id`, `overlord_monitor`.`app_user`.`username`, `overlord_monitor`.`app_user`.`role`, `overlord_monitor`.`app_user`.`enabled`, `overlord_monitor`.`app_user`.`must_change_password`, `overlord_monitor`.`app_user`.`locked_by_admin`, `anmeldung`.`letzte_anmeldung` from `overlord_monitor`.`app_user` left outer join (select `overlord_monitor`.`audit_log`.`actor_user_id`, max(`overlord_monitor`.`audit_log`.`occurred_at`) as `letzte_anmeldung` from `overlord_monitor`.`audit_log` where (`overlord_monitor`.`audit_log`.`event_type` = 'ANMELDUNG_ERFOLG' and `overlord_monitor`.`audit_log`.`actor_user_id` is not null) group by `overlord_monitor`.`audit_log`.`actor_user_id`) as `anmeldung` on `anmeldung`.`actor_user_id` = `overlord_monitor`.`app_user`.`id` order by `overlord_monitor`.`app_user`.`username`;
show profiles;
select now() as serverzeit_ende, @@global.read_only as read_only_ende;
