/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUser;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.app_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.role</code>.
     */
    public void setRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.must_change_password</code>.
     */
    public void setMustChangePassword(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.must_change_password</code>.
     */
    public Boolean getMustChangePassword() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.download_allowed</code>.
     */
    public void setDownloadAllowed(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.download_allowed</code>.
     */
    public Boolean getDownloadAllowed() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.failed_attempts</code>.
     */
    public void setFailedAttempts(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.failed_attempts</code>.
     */
    public Integer getFailedAttempts() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.locked_until</code>.
     */
    public void setLockedUntil(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.locked_until</code>.
     */
    public LocalDateTime getLockedUntil() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.last_login_at</code>.
     */
    public void setLastLoginAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.last_login_at</code>.
     */
    public LocalDateTime getLastLoginAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>overlord_monitor.app_user.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(Long id, String username, String passwordHash, String role, Boolean enabled, Boolean mustChangePassword, Boolean downloadAllowed, Integer failedAttempts, LocalDateTime lockedUntil, LocalDateTime lastLoginAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(AppUser.APP_USER);

        setId(id);
        setUsername(username);
        setPasswordHash(passwordHash);
        setRole(role);
        setEnabled(enabled);
        setMustChangePassword(mustChangePassword);
        setDownloadAllowed(downloadAllowed);
        setFailedAttempts(failedAttempts);
        setLockedUntil(lockedUntil);
        setLastLoginAt(lastLoginAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
