/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUserMandant;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserMandantRecord extends UpdatableRecordImpl<AppUserMandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.app_user_mandant.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user_mandant.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.app_user_mandant.mandant_id</code>.
     */
    public void setMandantId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.app_user_mandant.mandant_id</code>.
     */
    public String getMandantId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserMandantRecord
     */
    public AppUserMandantRecord() {
        super(AppUserMandant.APP_USER_MANDANT);
    }

    /**
     * Create a detached, initialised AppUserMandantRecord
     */
    public AppUserMandantRecord(Long userId, String mandantId) {
        super(AppUserMandant.APP_USER_MANDANT);

        setUserId(userId);
        setMandantId(mandantId);
        resetTouchedOnNotNull();
    }
}
