/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AuditLog;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditLogRecord extends UpdatableRecordImpl<AuditLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.audit_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.occurred_at</code>.
     */
    public void setOccurredAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.occurred_at</code>.
     */
    public LocalDateTime getOccurredAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.event_type</code>.
     */
    public void setEventType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.event_type</code>.
     */
    public String getEventType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.actor_user_id</code>.
     */
    public void setActorUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.actor_user_id</code>.
     */
    public Long getActorUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.actor_username</code>.
     */
    public void setActorUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.actor_username</code>.
     */
    public String getActorUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.mandant_id</code>.
     */
    public void setMandantId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.mandant_id</code>.
     */
    public String getMandantId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.target_type</code>.
     */
    public void setTargetType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.target_type</code>.
     */
    public String getTargetType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.target_id</code>.
     */
    public void setTargetId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.target_id</code>.
     */
    public String getTargetId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.ip</code>.
     */
    public void setIp(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.ip</code>.
     */
    public String getIp() {
        return (String) get(8);
    }

    /**
     * Setter for <code>overlord_monitor.audit_log.detail</code>.
     */
    public void setDetail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>overlord_monitor.audit_log.detail</code>.
     */
    public String getDetail() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditLogRecord
     */
    public AuditLogRecord() {
        super(AuditLog.AUDIT_LOG);
    }

    /**
     * Create a detached, initialised AuditLogRecord
     */
    public AuditLogRecord(Long id, LocalDateTime occurredAt, String eventType, Long actorUserId, String actorUsername, String mandantId, String targetType, String targetId, String ip, String detail) {
        super(AuditLog.AUDIT_LOG);

        setId(id);
        setOccurredAt(occurredAt);
        setEventType(eventType);
        setActorUserId(actorUserId);
        setActorUsername(actorUsername);
        setMandantId(mandantId);
        setTargetType(targetType);
        setTargetId(targetId);
        setIp(ip);
        setDetail(detail);
        resetTouchedOnNotNull();
    }
}
