/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSollaenge;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BamSollaengeRecord extends UpdatableRecordImpl<BamSollaengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.bam_sollaenge.mandant_id</code>.
     */
    public void setMandantId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_sollaenge.mandant_id</code>.
     */
    public String getMandantId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.bam_sollaenge.message_bam_type</code>.
     */
    public void setMessageBamType(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_sollaenge.message_bam_type</code>.
     */
    public Short getMessageBamType() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.bam_sollaenge.sollaenge</code>.
     */
    public void setSollaenge(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_sollaenge.sollaenge</code>.
     */
    public UByte getSollaenge() {
        return (UByte) get(2);
    }

    /**
     * Setter for
     * <code>overlord_monitor.bam_sollaenge.fuehrendes_leerzeichen</code>.
     */
    public void setFuehrendesLeerzeichen(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>overlord_monitor.bam_sollaenge.fuehrendes_leerzeichen</code>.
     */
    public Boolean getFuehrendesLeerzeichen() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>overlord_monitor.bam_sollaenge.dominanz_prozent</code>.
     */
    public void setDominanzProzent(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_sollaenge.dominanz_prozent</code>.
     */
    public BigDecimal getDominanzProzent() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>overlord_monitor.bam_sollaenge.leerzeichen_prozent</code>.
     */
    public void setLeerzeichenProzent(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>overlord_monitor.bam_sollaenge.leerzeichen_prozent</code>.
     */
    public BigDecimal getLeerzeichenProzent() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>overlord_monitor.bam_sollaenge.zeilen</code>.
     */
    public void setZeilen(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_sollaenge.zeilen</code>.
     */
    public Integer getZeilen() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>overlord_monitor.bam_sollaenge.gemessen_am</code>.
     */
    public void setGemessenAm(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_sollaenge.gemessen_am</code>.
     */
    public LocalDate getGemessenAm() {
        return (LocalDate) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BamSollaengeRecord
     */
    public BamSollaengeRecord() {
        super(BamSollaenge.BAM_SOLLAENGE);
    }

    /**
     * Create a detached, initialised BamSollaengeRecord
     */
    public BamSollaengeRecord(String mandantId, Short messageBamType, UByte sollaenge, Boolean fuehrendesLeerzeichen, BigDecimal dominanzProzent, BigDecimal leerzeichenProzent, Integer zeilen, LocalDate gemessenAm) {
        super(BamSollaenge.BAM_SOLLAENGE);

        setMandantId(mandantId);
        setMessageBamType(messageBamType);
        setSollaenge(sollaenge);
        setFuehrendesLeerzeichen(fuehrendesLeerzeichen);
        setDominanzProzent(dominanzProzent);
        setLeerzeichenProzent(leerzeichenProzent);
        setZeilen(zeilen);
        setGemessenAm(gemessenAm);
        resetTouchedOnNotNull();
    }
}
