/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.BamSpalte;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BamSpalteRecord extends UpdatableRecordImpl<BamSpalteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.bam_spalte.mandant_id</code>.
     */
    public void setMandantId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_spalte.mandant_id</code>.
     */
    public String getMandantId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.bam_spalte.position</code>.
     */
    public void setPosition(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_spalte.position</code>.
     */
    public Byte getPosition() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.bam_spalte.message_bam_type</code>.
     */
    public void setMessageBamType(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.bam_spalte.message_bam_type</code>.
     */
    public Short getMessageBamType() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Byte> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BamSpalteRecord
     */
    public BamSpalteRecord() {
        super(BamSpalte.BAM_SPALTE);
    }

    /**
     * Create a detached, initialised BamSpalteRecord
     */
    public BamSpalteRecord(String mandantId, Byte position, Short messageBamType) {
        super(BamSpalte.BAM_SPALTE);

        setMandantId(mandantId);
        setPosition(position);
        setMessageBamType(messageBamType);
        resetTouchedOnNotNull();
    }
}
