/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollup;

import java.time.LocalDateTime;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRollupRecord extends UpdatableRecordImpl<MessageRollupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.message_rollup.stunde</code>.
     */
    public void setStunde(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup.stunde</code>.
     */
    public LocalDateTime getStunde() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.message_rollup.process_id</code>.
     */
    public void setProcessId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup.process_id</code>.
     */
    public String getProcessId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.message_rollup.message_status</code>.
     */
    public void setMessageStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup.message_status</code>.
     */
    public String getMessageStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>overlord_monitor.message_rollup.anzahl</code>.
     */
    public void setAnzahl(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup.anzahl</code>.
     */
    public Integer getAnzahl() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<LocalDateTime, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRollupRecord
     */
    public MessageRollupRecord() {
        super(MessageRollup.MESSAGE_ROLLUP);
    }

    /**
     * Create a detached, initialised MessageRollupRecord
     */
    public MessageRollupRecord(LocalDateTime stunde, String processId, String messageStatus, Integer anzahl) {
        super(MessageRollup.MESSAGE_ROLLUP);

        setStunde(stunde);
        setProcessId(processId);
        setMessageStatus(messageStatus);
        setAnzahl(anzahl);
        resetTouchedOnNotNull();
    }
}
