/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.MessageRollupMonat;

import java.time.LocalDate;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRollupMonatRecord extends UpdatableRecordImpl<MessageRollupMonatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.message_rollup_monat.monat</code>.
     */
    public void setMonat(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup_monat.monat</code>.
     */
    public LocalDate getMonat() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.message_rollup_monat.process_id</code>.
     */
    public void setProcessId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup_monat.process_id</code>.
     */
    public String getProcessId() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>overlord_monitor.message_rollup_monat.message_status</code>.
     */
    public void setMessageStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>overlord_monitor.message_rollup_monat.message_status</code>.
     */
    public String getMessageStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>overlord_monitor.message_rollup_monat.anzahl</code>.
     */
    public void setAnzahl(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>overlord_monitor.message_rollup_monat.anzahl</code>.
     */
    public Integer getAnzahl() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<LocalDate, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRollupMonatRecord
     */
    public MessageRollupMonatRecord() {
        super(MessageRollupMonat.MESSAGE_ROLLUP_MONAT);
    }

    /**
     * Create a detached, initialised MessageRollupMonatRecord
     */
    public MessageRollupMonatRecord(LocalDate monat, String processId, String messageStatus, Integer anzahl) {
        super(MessageRollupMonat.MESSAGE_ROLLUP_MONAT);

        setMonat(monat);
        setProcessId(processId);
        setMessageStatus(messageStatus);
        setAnzahl(anzahl);
        resetTouchedOnNotNull();
    }
}
