/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.ProcessCatalog;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessCatalogRecord extends UpdatableRecordImpl<ProcessCatalogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.process_catalog.process_id</code>.
     */
    public void setProcessId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.process_catalog.process_id</code>.
     */
    public String getProcessId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.process_catalog.partner</code>.
     */
    public void setPartner(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.process_catalog.partner</code>.
     */
    public String getPartner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.process_catalog.richtung</code>.
     */
    public void setRichtung(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.process_catalog.richtung</code>.
     */
    public String getRichtung() {
        return (String) get(2);
    }

    /**
     * Setter for <code>overlord_monitor.process_catalog.pflegestatus</code>.
     */
    public void setPflegestatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>overlord_monitor.process_catalog.pflegestatus</code>.
     */
    public String getPflegestatus() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>overlord_monitor.process_catalog.vorschlag_herkunft</code>.
     */
    public void setVorschlagHerkunft(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>overlord_monitor.process_catalog.vorschlag_herkunft</code>.
     */
    public String getVorschlagHerkunft() {
        return (String) get(4);
    }

    /**
     * Setter for <code>overlord_monitor.process_catalog.geaendert_am</code>.
     */
    public void setGeaendertAm(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>overlord_monitor.process_catalog.geaendert_am</code>.
     */
    public LocalDateTime getGeaendertAm() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>overlord_monitor.process_catalog.geaendert_von</code>.
     */
    public void setGeaendertVon(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>overlord_monitor.process_catalog.geaendert_von</code>.
     */
    public String getGeaendertVon() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>overlord_monitor.process_catalog.traegt_nachrichten</code>.
     */
    public void setTraegtNachrichten(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>overlord_monitor.process_catalog.traegt_nachrichten</code>.
     */
    public Boolean getTraegtNachrichten() {
        return (Boolean) get(7);
    }

    /**
     * Setter for
     * <code>overlord_monitor.process_catalog.bestand_geprueft_am</code>.
     */
    public void setBestandGeprueftAm(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>overlord_monitor.process_catalog.bestand_geprueft_am</code>.
     */
    public LocalDateTime getBestandGeprueftAm() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessCatalogRecord
     */
    public ProcessCatalogRecord() {
        super(ProcessCatalog.PROCESS_CATALOG);
    }

    /**
     * Create a detached, initialised ProcessCatalogRecord
     */
    public ProcessCatalogRecord(String processId, String partner, String richtung, String pflegestatus, String vorschlagHerkunft, LocalDateTime geaendertAm, String geaendertVon, Boolean traegtNachrichten, LocalDateTime bestandGeprueftAm) {
        super(ProcessCatalog.PROCESS_CATALOG);

        setProcessId(processId);
        setPartner(partner);
        setRichtung(richtung);
        setPflegestatus(pflegestatus);
        setVorschlagHerkunft(vorschlagHerkunft);
        setGeaendertAm(geaendertAm);
        setGeaendertVon(geaendertVon);
        setTraegtNachrichten(traegtNachrichten);
        setBestandGeprueftAm(bestandGeprueftAm);
        resetTouchedOnNotNull();
    }
}
