/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.RollupLauf;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RollupLaufRecord extends UpdatableRecordImpl<RollupLaufRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.art</code>.
     */
    public void setArt(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.art</code>.
     */
    public String getArt() {
        return (String) get(1);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.fenster_von</code>.
     */
    public void setFensterVon(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.fenster_von</code>.
     */
    public LocalDateTime getFensterVon() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.fenster_bis</code>.
     */
    public void setFensterBis(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.fenster_bis</code>.
     */
    public LocalDateTime getFensterBis() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.gestartet_am</code>.
     */
    public void setGestartetAm(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.gestartet_am</code>.
     */
    public LocalDateTime getGestartetAm() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.beendet_am</code>.
     */
    public void setBeendetAm(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.beendet_am</code>.
     */
    public LocalDateTime getBeendetAm() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.zeilen_geschrieben</code>.
     */
    public void setZeilenGeschrieben(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.zeilen_geschrieben</code>.
     */
    public Integer getZeilenGeschrieben() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>overlord_monitor.rollup_lauf.fehler</code>.
     */
    public void setFehler(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>overlord_monitor.rollup_lauf.fehler</code>.
     */
    public String getFehler() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RollupLaufRecord
     */
    public RollupLaufRecord() {
        super(RollupLauf.ROLLUP_LAUF);
    }

    /**
     * Create a detached, initialised RollupLaufRecord
     */
    public RollupLaufRecord(Long id, String art, LocalDateTime fensterVon, LocalDateTime fensterBis, LocalDateTime gestartetAm, LocalDateTime beendetAm, Integer zeilenGeschrieben, String fehler) {
        super(RollupLauf.ROLLUP_LAUF);

        setId(id);
        setArt(art);
        setFensterVon(fensterVon);
        setFensterBis(fensterBis);
        setGestartetAm(gestartetAm);
        setBeendetAm(beendetAm);
        setZeilenGeschrieben(zeilenGeschrieben);
        setFehler(fehler);
        resetTouchedOnNotNull();
    }
}
