/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Mandant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MandantRecord extends UpdatableRecordImpl<MandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.Mandant.MandantID</code>.
     */
    public void setMandantid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.Mandant.MandantID</code>.
     */
    public String getMandantid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.Mandant.MandantName</code>.
     */
    public void setMandantname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.Mandant.MandantName</code>.
     */
    public String getMandantname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.Mandant.MandantDescription</code>.
     */
    public void setMandantdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.Mandant.MandantDescription</code>.
     */
    public String getMandantdescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MandantRecord
     */
    public MandantRecord() {
        super(Mandant.MANDANT);
    }

    /**
     * Create a detached, initialised MandantRecord
     */
    public MandantRecord(String mandantid, String mandantname, String mandantdescription) {
        super(Mandant.MANDANT);

        setMandantid(mandantid);
        setMandantname(mandantname);
        setMandantdescription(mandantdescription);
        resetTouchedOnNotNull();
    }
}
