/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageaction;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageactionRecord extends UpdatableRecordImpl<MessageactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageAction.MessageID</code>.
     */
    public void setMessageid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.MessageID</code>.
     */
    public String getMessageid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.MessageActionID</code>.
     */
    public void setMessageactionid(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.MessageActionID</code>.
     */
    public Short getMessageactionid() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.SOSID</code>.
     */
    public void setSosid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.SOSID</code>.
     */
    public String getSosid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.SOSActionID</code>.
     */
    public void setSosactionid(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.SOSActionID</code>.
     */
    public Short getSosactionid() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.MessageActionStart</code>.
     */
    public void setMessageactionstart(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.MessageActionStart</code>.
     */
    public LocalDateTime getMessageactionstart() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.MessageActionEnd</code>.
     */
    public void setMessageactionend(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.MessageActionEnd</code>.
     */
    public LocalDateTime getMessageactionend() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.ServiceID</code>.
     */
    public void setServiceid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.ServiceID</code>.
     */
    public String getServiceid() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>GlassfishDB.MessageAction.SOSActionServiceProperties</code>.
     */
    public void setSosactionserviceproperties(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.MessageAction.SOSActionServiceProperties</code>.
     */
    public String getSosactionserviceproperties() {
        return (String) get(7);
    }

    /**
     * Setter for <code>GlassfishDB.MessageAction.SOSActionTimeout</code>.
     */
    public void setSosactiontimeout(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageAction.SOSActionTimeout</code>.
     */
    public Short getSosactiontimeout() {
        return (Short) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageactionRecord
     */
    public MessageactionRecord() {
        super(Messageaction.MESSAGEACTION);
    }

    /**
     * Create a detached, initialised MessageactionRecord
     */
    public MessageactionRecord(String messageid, Short messageactionid, String sosid, Short sosactionid, LocalDateTime messageactionstart, LocalDateTime messageactionend, String serviceid, String sosactionserviceproperties, Short sosactiontimeout) {
        super(Messageaction.MESSAGEACTION);

        setMessageid(messageid);
        setMessageactionid(messageactionid);
        setSosid(sosid);
        setSosactionid(sosactionid);
        setMessageactionstart(messageactionstart);
        setMessageactionend(messageactionend);
        setServiceid(serviceid);
        setSosactionserviceproperties(sosactionserviceproperties);
        setSosactiontimeout(sosactiontimeout);
        resetTouchedOnNotNull();
    }
}
