/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagemandantid;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagemandantidRecord extends TableRecordImpl<MessagemandantidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageMandantID.MessageID</code>.
     */
    public void setMessageid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageMandantID.MessageID</code>.
     */
    public String getMessageid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.MessageMandantID.MandantID</code>.
     */
    public void setMandantid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageMandantID.MandantID</code>.
     */
    public String getMandantid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagemandantidRecord
     */
    public MessagemandantidRecord() {
        super(Messagemandantid.MESSAGEMANDANTID);
    }

    /**
     * Create a detached, initialised MessagemandantidRecord
     */
    public MessagemandantidRecord(String messageid, String mandantid) {
        super(Messagemandantid.MESSAGEMANDANTID);

        setMessageid(messageid);
        setMandantid(mandantid);
        resetTouchedOnNotNull();
    }
}
