/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebam;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagebamRecord extends UpdatableRecordImpl<MessagebamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageBAM.MessageID</code>.
     */
    public void setMessageid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageBAM.MessageID</code>.
     */
    public String getMessageid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.MessageBAM.MessageBAMType</code>.
     */
    public void setMessagebamtype(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageBAM.MessageBAMType</code>.
     */
    public Short getMessagebamtype() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.MessageBAM.MessageBAMValue</code>.
     */
    public void setMessagebamvalue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageBAM.MessageBAMValue</code>.
     */
    public String getMessagebamvalue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, Short, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagebamRecord
     */
    public MessagebamRecord() {
        super(Messagebam.MESSAGEBAM);
    }

    /**
     * Create a detached, initialised MessagebamRecord
     */
    public MessagebamRecord(String messageid, Short messagebamtype, String messagebamvalue) {
        super(Messagebam.MESSAGEBAM);

        setMessageid(messageid);
        setMessagebamtype(messagebamtype);
        setMessagebamvalue(messagebamvalue);
        resetTouchedOnNotNull();
    }
}
