/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebammandant;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagebammandantRecord extends UpdatableRecordImpl<MessagebammandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageBAMMandant.MessageBAMType</code>.
     */
    public void setMessagebamtype(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageBAMMandant.MessageBAMType</code>.
     */
    public Short getMessagebamtype() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.MessageBAMMandant.MandantID</code>.
     */
    public void setMandantid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageBAMMandant.MandantID</code>.
     */
    public String getMandantid() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>GlassfishDB.MessageBAMMandant.MessageBAMTypeSortIndex</code>.
     */
    public void setMessagebamtypesortindex(Short value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.MessageBAMMandant.MessageBAMTypeSortIndex</code>.
     */
    public Short getMessagebamtypesortindex() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagebammandantRecord
     */
    public MessagebammandantRecord() {
        super(Messagebammandant.MESSAGEBAMMANDANT);
    }

    /**
     * Create a detached, initialised MessagebammandantRecord
     */
    public MessagebammandantRecord(Short messagebamtype, String mandantid, Short messagebamtypesortindex) {
        super(Messagebammandant.MESSAGEBAMMANDANT);

        setMessagebamtype(messagebamtype);
        setMandantid(mandantid);
        setMessagebamtypesortindex(messagebamtypesortindex);
        resetTouchedOnNotNull();
    }
}
