/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagepropertysearchlistentry;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagepropertysearchlistentryRecord extends UpdatableRecordImpl<MessagepropertysearchlistentryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>GlassfishDB.MessagePropertySearchListEntry.MessagePropertyName</code>.
     */
    public void setMessagepropertyname(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.MessagePropertySearchListEntry.MessagePropertyName</code>.
     */
    public String getMessagepropertyname() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>GlassfishDB.MessagePropertySearchListEntry.MandantID</code>.
     */
    public void setMandantid(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.MessagePropertySearchListEntry.MandantID</code>.
     */
    public String getMandantid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagepropertysearchlistentryRecord
     */
    public MessagepropertysearchlistentryRecord() {
        super(Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY);
    }

    /**
     * Create a detached, initialised MessagepropertysearchlistentryRecord
     */
    public MessagepropertysearchlistentryRecord(String messagepropertyname, String mandantid) {
        super(Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY);

        setMessagepropertyname(messagepropertyname);
        setMandantid(mandantid);
        resetTouchedOnNotNull();
    }
}
