/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Message;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.Message.MessageID</code>.
     */
    public void setMessageid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.MessageID</code>.
     */
    public String getMessageid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.Message.SOSID</code>.
     */
    public void setSosid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.SOSID</code>.
     */
    public String getSosid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.Message.SOSActionID</code>.
     */
    public void setSosactionid(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.SOSActionID</code>.
     */
    public Short getSosactionid() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.Message.MessageLastUpdate</code>.
     */
    public void setMessagelastupdate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.MessageLastUpdate</code>.
     */
    public LocalDateTime getMessagelastupdate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>GlassfishDB.Message.MessageTimeout</code>.
     */
    public void setMessagetimeout(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.MessageTimeout</code>.
     */
    public Short getMessagetimeout() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>GlassfishDB.Message.MessageStatus</code>.
     */
    public void setMessagestatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.MessageStatus</code>.
     */
    public String getMessagestatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>GlassfishDB.Message.SourceMessageID</code>.
     */
    public void setSourcemessageid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.SourceMessageID</code>.
     */
    public String getSourcemessageid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>GlassfishDB.Message.TargetMessageID</code>.
     */
    public void setTargetmessageid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.TargetMessageID</code>.
     */
    public String getTargetmessageid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>GlassfishDB.Message.ProcessID</code>.
     */
    public void setProcessid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.ProcessID</code>.
     */
    public String getProcessid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>GlassfishDB.Message.Source</code>.
     */
    public void setSource(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.Source</code>.
     */
    public Boolean getSource() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>GlassfishDB.Message.Target</code>.
     */
    public void setTarget(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>GlassfishDB.Message.Target</code>.
     */
    public Boolean getTarget() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(String messageid, String sosid, Short sosactionid, LocalDateTime messagelastupdate, Short messagetimeout, String messagestatus, String sourcemessageid, String targetmessageid, String processid, Boolean source, Boolean target) {
        super(Message.MESSAGE);

        setMessageid(messageid);
        setSosid(sosid);
        setSosactionid(sosactionid);
        setMessagelastupdate(messagelastupdate);
        setMessagetimeout(messagetimeout);
        setMessagestatus(messagestatus);
        setSourcemessageid(sourcemessageid);
        setTargetmessageid(targetmessageid);
        setProcessid(processid);
        setSource(source);
        setTarget(target);
        resetTouchedOnNotNull();
    }
}
