/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebamtype;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagebamtypeRecord extends UpdatableRecordImpl<MessagebamtypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageBAMType.MessageBAMType</code>.
     */
    public void setMessagebamtype(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageBAMType.MessageBAMType</code>.
     */
    public Short getMessagebamtype() {
        return (Short) get(0);
    }

    /**
     * Setter for
     * <code>GlassfishDB.MessageBAMType.MessageBAMTypeDescription</code>.
     */
    public void setMessagebamtypedescription(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.MessageBAMType.MessageBAMTypeDescription</code>.
     */
    public String getMessagebamtypedescription() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagebamtypeRecord
     */
    public MessagebamtypeRecord() {
        super(Messagebamtype.MESSAGEBAMTYPE);
    }

    /**
     * Create a detached, initialised MessagebamtypeRecord
     */
    public MessagebamtypeRecord(Short messagebamtype, String messagebamtypedescription) {
        super(Messagebamtype.MESSAGEBAMTYPE);

        setMessagebamtype(messagebamtype);
        setMessagebamtypedescription(messagebamtypedescription);
        resetTouchedOnNotNull();
    }
}
