/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistichistory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagestatistichistoryRecord extends UpdatableRecordImpl<MessagestatistichistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageStatisticHistory.Period</code>.
     */
    public void setPeriod(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageStatisticHistory.Period</code>.
     */
    public String getPeriod() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>GlassfishDB.MessageStatisticHistory.NumberOfMessages</code>.
     */
    public void setNumberofmessages(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.MessageStatisticHistory.NumberOfMessages</code>.
     */
    public Long getNumberofmessages() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagestatistichistoryRecord
     */
    public MessagestatistichistoryRecord() {
        super(Messagestatistichistory.MESSAGESTATISTICHISTORY);
    }

    /**
     * Create a detached, initialised MessagestatistichistoryRecord
     */
    public MessagestatistichistoryRecord(String period, Long numberofmessages) {
        super(Messagestatistichistory.MESSAGESTATISTICHISTORY);

        setPeriod(period);
        setNumberofmessages(numberofmessages);
        resetTouchedOnNotNull();
    }
}
