/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistic;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagestatisticRecord extends TableRecordImpl<MessagestatisticRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageStatistic.Period</code>.
     */
    public void setPeriod(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageStatistic.Period</code>.
     */
    public String getPeriod() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.MessageStatistic.NumberOfMessages</code>.
     */
    public void setNumberofmessages(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageStatistic.NumberOfMessages</code>.
     */
    public Long getNumberofmessages() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagestatisticRecord
     */
    public MessagestatisticRecord() {
        super(Messagestatistic.MESSAGESTATISTIC);
    }

    /**
     * Create a detached, initialised MessagestatisticRecord
     */
    public MessagestatisticRecord(String period, Long numberofmessages) {
        super(Messagestatistic.MESSAGESTATISTIC);

        setPeriod(period);
        setNumberofmessages(numberofmessages);
        resetTouchedOnNotNull();
    }
}
