/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageproperty;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagepropertyRecord extends UpdatableRecordImpl<MessagepropertyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.MessageProperty.MessageID</code>.
     */
    public void setMessageid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageProperty.MessageID</code>.
     */
    public String getMessageid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.MessageProperty.MessageActionID</code>.
     */
    public void setMessageactionid(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageProperty.MessageActionID</code>.
     */
    public Short getMessageactionid() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.MessageProperty.MessagePropertyName</code>.
     */
    public void setMessagepropertyname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageProperty.MessagePropertyName</code>.
     */
    public String getMessagepropertyname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.MessageProperty.MessagePropertyValue</code>.
     */
    public void setMessagepropertyvalue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.MessageProperty.MessagePropertyValue</code>.
     */
    public String getMessagepropertyvalue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, Short> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagepropertyRecord
     */
    public MessagepropertyRecord() {
        super(Messageproperty.MESSAGEPROPERTY);
    }

    /**
     * Create a detached, initialised MessagepropertyRecord
     */
    public MessagepropertyRecord(String messageid, Short messageactionid, String messagepropertyname, String messagepropertyvalue) {
        super(Messageproperty.MESSAGEPROPERTY);

        setMessageid(messageid);
        setMessageactionid(messageactionid);
        setMessagepropertyname(messagepropertyname);
        setMessagepropertyvalue(messagepropertyvalue);
        resetTouchedOnNotNull();
    }
}
