/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Process;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessRecord extends UpdatableRecordImpl<ProcessRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.Process.ProcessID</code>.
     */
    public void setProcessid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.Process.ProcessID</code>.
     */
    public String getProcessid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.Process.ProcessName</code>.
     */
    public void setProcessname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.Process.ProcessName</code>.
     */
    public String getProcessname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.Process.ProcessDescription</code>.
     */
    public void setProcessdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.Process.ProcessDescription</code>.
     */
    public String getProcessdescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.Process.ProjectID</code>.
     */
    public void setProjectid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.Process.ProjectID</code>.
     */
    public String getProjectid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessRecord
     */
    public ProcessRecord() {
        super(Process.PROCESS);
    }

    /**
     * Create a detached, initialised ProcessRecord
     */
    public ProcessRecord(String processid, String processname, String processdescription, String projectid) {
        super(Process.PROCESS);

        setProcessid(processid);
        setProcessname(processname);
        setProcessdescription(processdescription);
        setProjectid(projectid);
        resetTouchedOnNotNull();
    }
}
