/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Project;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.Project.ProjectID</code>.
     */
    public void setProjectid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.Project.ProjectID</code>.
     */
    public String getProjectid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.Project.ProjectName</code>.
     */
    public void setProjectname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.Project.ProjectName</code>.
     */
    public String getProjectname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.Project.ProjectDescription</code>.
     */
    public void setProjectdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.Project.ProjectDescription</code>.
     */
    public String getProjectdescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(String projectid, String projectname, String projectdescription) {
        super(Project.PROJECT);

        setProjectid(projectid);
        setProjectname(projectname);
        setProjectdescription(projectdescription);
        resetTouchedOnNotNull();
    }
}
