/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Projectmandant;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectmandantRecord extends UpdatableRecordImpl<ProjectmandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.ProjectMandant.ProjectID</code>.
     */
    public void setProjectid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.ProjectMandant.ProjectID</code>.
     */
    public String getProjectid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.ProjectMandant.MandantID</code>.
     */
    public void setMandantid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.ProjectMandant.MandantID</code>.
     */
    public String getMandantid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectmandantRecord
     */
    public ProjectmandantRecord() {
        super(Projectmandant.PROJECTMANDANT);
    }

    /**
     * Create a detached, initialised ProjectmandantRecord
     */
    public ProjectmandantRecord(String projectid, String mandantid) {
        super(Projectmandant.PROJECTMANDANT);

        setProjectid(projectid);
        setMandantid(mandantid);
        resetTouchedOnNotNull();
    }
}
