/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduleplans;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScheduleplansRecord extends UpdatableRecordImpl<ScheduleplansRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.SchedulePlans.ScheduleID</code>.
     */
    public void setScheduleid(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.SchedulePlans.ScheduleID</code>.
     */
    public Short getScheduleid() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.SchedulePlans.ActionID</code>.
     */
    public void setActionid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.SchedulePlans.ActionID</code>.
     */
    public String getActionid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleplansRecord
     */
    public ScheduleplansRecord() {
        super(Scheduleplans.SCHEDULEPLANS);
    }

    /**
     * Create a detached, initialised ScheduleplansRecord
     */
    public ScheduleplansRecord(Short scheduleid, String actionid) {
        super(Scheduleplans.SCHEDULEPLANS);

        setScheduleid(scheduleid);
        setActionid(actionid);
        resetTouchedOnNotNull();
    }
}
