/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Schedule;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScheduleRecord extends UpdatableRecordImpl<ScheduleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleID</code>.
     */
    public void setScheduleid(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleID</code>.
     */
    public Short getScheduleid() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleName</code>.
     */
    public void setSchedulename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleName</code>.
     */
    public String getSchedulename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleWeekDays</code>.
     */
    public void setScheduleweekdays(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleWeekDays</code>.
     */
    public String getScheduleweekdays() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleDays</code>.
     */
    public void setScheduledays(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleDays</code>.
     */
    public String getScheduledays() {
        return (String) get(3);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleMonths</code>.
     */
    public void setSchedulemonths(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleMonths</code>.
     */
    public String getSchedulemonths() {
        return (String) get(4);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleTimeFrom</code>.
     */
    public void setScheduletimefrom(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleTimeFrom</code>.
     */
    public String getScheduletimefrom() {
        return (String) get(5);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleTimeTo</code>.
     */
    public void setScheduletimeto(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleTimeTo</code>.
     */
    public String getScheduletimeto() {
        return (String) get(6);
    }

    /**
     * Setter for <code>GlassfishDB.Schedule.ScheduleTimeRepeat</code>.
     */
    public void setScheduletimerepeat(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>GlassfishDB.Schedule.ScheduleTimeRepeat</code>.
     */
    public Short getScheduletimerepeat() {
        return (Short) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleRecord
     */
    public ScheduleRecord() {
        super(Schedule.SCHEDULE);
    }

    /**
     * Create a detached, initialised ScheduleRecord
     */
    public ScheduleRecord(Short scheduleid, String schedulename, String scheduleweekdays, String scheduledays, String schedulemonths, String scheduletimefrom, String scheduletimeto, Short scheduletimerepeat) {
        super(Schedule.SCHEDULE);

        setScheduleid(scheduleid);
        setSchedulename(schedulename);
        setScheduleweekdays(scheduleweekdays);
        setScheduledays(scheduledays);
        setSchedulemonths(schedulemonths);
        setScheduletimefrom(scheduletimefrom);
        setScheduletimeto(scheduletimeto);
        setScheduletimerepeat(scheduletimerepeat);
        resetTouchedOnNotNull();
    }
}
