/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduletasks;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScheduletasksRecord extends UpdatableRecordImpl<ScheduletasksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.ScheduleTasks.ActionID</code>.
     */
    public void setActionid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.ScheduleTasks.ActionID</code>.
     */
    public String getActionid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.ScheduleTasks.Execution</code>.
     */
    public void setExecution(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.ScheduleTasks.Execution</code>.
     */
    public LocalDateTime getExecution() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, LocalDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduletasksRecord
     */
    public ScheduletasksRecord() {
        super(Scheduletasks.SCHEDULETASKS);
    }

    /**
     * Create a detached, initialised ScheduletasksRecord
     */
    public ScheduletasksRecord(String actionid, LocalDateTime execution) {
        super(Scheduletasks.SCHEDULETASKS);

        setActionid(actionid);
        setExecution(execution);
        resetTouchedOnNotNull();
    }
}
