/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetask;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServicetaskRecord extends UpdatableRecordImpl<ServicetaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.ServiceTask.ServiceID</code>.
     */
    public void setServiceid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceTask.ServiceID</code>.
     */
    public String getServiceid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.ServiceTask.ServiceTaskID</code>.
     */
    public void setServicetaskid(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceTask.ServiceTaskID</code>.
     */
    public Short getServicetaskid() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.ServiceTask.ServiceTaskName</code>.
     */
    public void setServicetaskname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceTask.ServiceTaskName</code>.
     */
    public String getServicetaskname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.ServiceTask.ServiceTaskProperties</code>.
     */
    public void setServicetaskproperties(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceTask.ServiceTaskProperties</code>.
     */
    public String getServicetaskproperties() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicetaskRecord
     */
    public ServicetaskRecord() {
        super(Servicetask.SERVICETASK);
    }

    /**
     * Create a detached, initialised ServicetaskRecord
     */
    public ServicetaskRecord(String serviceid, Short servicetaskid, String servicetaskname, String servicetaskproperties) {
        super(Servicetask.SERVICETASK);

        setServiceid(serviceid);
        setServicetaskid(servicetaskid);
        setServicetaskname(servicetaskname);
        setServicetaskproperties(servicetaskproperties);
        resetTouchedOnNotNull();
    }
}
