/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicegroup;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServicegroupRecord extends UpdatableRecordImpl<ServicegroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.ServiceGroup.ServiceGroupID</code>.
     */
    public void setServicegroupid(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceGroup.ServiceGroupID</code>.
     */
    public Short getServicegroupid() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.ServiceGroup.ServiceGroupName</code>.
     */
    public void setServicegroupname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceGroup.ServiceGroupName</code>.
     */
    public String getServicegroupname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicegroupRecord
     */
    public ServicegroupRecord() {
        super(Servicegroup.SERVICEGROUP);
    }

    /**
     * Create a detached, initialised ServicegroupRecord
     */
    public ServicegroupRecord(Short servicegroupid, String servicegroupname) {
        super(Servicegroup.SERVICEGROUP);

        setServicegroupid(servicegroupid);
        setServicegroupname(servicegroupname);
        resetTouchedOnNotNull();
    }
}
