/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Service;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServiceRecord extends UpdatableRecordImpl<ServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.Service.ServiceID</code>.
     */
    public void setServiceid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceID</code>.
     */
    public String getServiceid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceTypeID</code>.
     */
    public void setServicetypeid(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceTypeID</code>.
     */
    public Short getServicetypeid() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceConnectString</code>.
     */
    public void setServiceconnectstring(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceConnectString</code>.
     */
    public String getServiceconnectstring() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceName</code>.
     */
    public void setServicename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceName</code>.
     */
    public String getServicename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceDescription</code>.
     */
    public void setServicedescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceDescription</code>.
     */
    public String getServicedescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceStatus</code>.
     */
    public void setServicestatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceStatus</code>.
     */
    public String getServicestatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceLastUpdate</code>.
     */
    public void setServicelastupdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceLastUpdate</code>.
     */
    public LocalDateTime getServicelastupdate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceLastStatusMessage</code>.
     */
    public void setServicelaststatusmessage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceLastStatusMessage</code>.
     */
    public String getServicelaststatusmessage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceTimeout</code>.
     */
    public void setServicetimeout(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceTimeout</code>.
     */
    public Short getServicetimeout() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>GlassfishDB.Service.ServiceDefaultFileStore</code>.
     */
    public void setServicedefaultfilestore(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>GlassfishDB.Service.ServiceDefaultFileStore</code>.
     */
    public String getServicedefaultfilestore() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceRecord
     */
    public ServiceRecord() {
        super(Service.SERVICE);
    }

    /**
     * Create a detached, initialised ServiceRecord
     */
    public ServiceRecord(String serviceid, Short servicetypeid, String serviceconnectstring, String servicename, String servicedescription, String servicestatus, LocalDateTime servicelastupdate, String servicelaststatusmessage, Short servicetimeout, String servicedefaultfilestore) {
        super(Service.SERVICE);

        setServiceid(serviceid);
        setServicetypeid(servicetypeid);
        setServiceconnectstring(serviceconnectstring);
        setServicename(servicename);
        setServicedescription(servicedescription);
        setServicestatus(servicestatus);
        setServicelastupdate(servicelastupdate);
        setServicelaststatusmessage(servicelaststatusmessage);
        setServicetimeout(servicetimeout);
        setServicedefaultfilestore(servicedefaultfilestore);
        resetTouchedOnNotNull();
    }
}
