/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetype;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServicetypeRecord extends UpdatableRecordImpl<ServicetypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.ServiceType.ServiceTypeID</code>.
     */
    public void setServicetypeid(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceType.ServiceTypeID</code>.
     */
    public Short getServicetypeid() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.ServiceType.ServiceTypeName</code>.
     */
    public void setServicetypename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceType.ServiceTypeName</code>.
     */
    public String getServicetypename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.ServiceType.ServiceGroupID</code>.
     */
    public void setServicegroupid(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.ServiceType.ServiceGroupID</code>.
     */
    public Short getServicegroupid() {
        return (Short) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicetypeRecord
     */
    public ServicetypeRecord() {
        super(Servicetype.SERVICETYPE);
    }

    /**
     * Create a detached, initialised ServicetypeRecord
     */
    public ServicetypeRecord(Short servicetypeid, String servicetypename, Short servicegroupid) {
        super(Servicetype.SERVICETYPE);

        setServicetypeid(servicetypeid);
        setServicetypename(servicetypename);
        setServicegroupid(servicegroupid);
        resetTouchedOnNotNull();
    }
}
