/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosaction;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SosactionRecord extends UpdatableRecordImpl<SosactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.SOSAction.SOSID</code>.
     */
    public void setSosid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSAction.SOSID</code>.
     */
    public String getSosid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.SOSAction.SOSActionID</code>.
     */
    public void setSosactionid(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSAction.SOSActionID</code>.
     */
    public Short getSosactionid() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.SOSAction.SOSActionName</code>.
     */
    public void setSosactionname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSAction.SOSActionName</code>.
     */
    public String getSosactionname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.SOSAction.ServiceID</code>.
     */
    public void setServiceid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSAction.ServiceID</code>.
     */
    public String getServiceid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>GlassfishDB.SOSAction.SOSActionServiceProperties</code>.
     */
    public void setSosactionserviceproperties(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSAction.SOSActionServiceProperties</code>.
     */
    public String getSosactionserviceproperties() {
        return (String) get(4);
    }

    /**
     * Setter for <code>GlassfishDB.SOSAction.SOSActionTimeout</code>.
     */
    public void setSosactiontimeout(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSAction.SOSActionTimeout</code>.
     */
    public Short getSosactiontimeout() {
        return (Short) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SosactionRecord
     */
    public SosactionRecord() {
        super(Sosaction.SOSACTION);
    }

    /**
     * Create a detached, initialised SosactionRecord
     */
    public SosactionRecord(String sosid, Short sosactionid, String sosactionname, String serviceid, String sosactionserviceproperties, Short sosactiontimeout) {
        super(Sosaction.SOSACTION);

        setSosid(sosid);
        setSosactionid(sosactionid);
        setSosactionname(sosactionname);
        setServiceid(serviceid);
        setSosactionserviceproperties(sosactionserviceproperties);
        setSosactiontimeout(sosactiontimeout);
        resetTouchedOnNotNull();
    }
}
