/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosdefaultmessageproperty;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SosdefaultmessagepropertyRecord extends UpdatableRecordImpl<SosdefaultmessagepropertyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.SOSDefaultMessageProperty.SOSID</code>.
     */
    public void setSosid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOSDefaultMessageProperty.SOSID</code>.
     */
    public String getSosid() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>GlassfishDB.SOSDefaultMessageProperty.MessagePropertyName</code>.
     */
    public void setMessagepropertyname(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.SOSDefaultMessageProperty.MessagePropertyName</code>.
     */
    public String getMessagepropertyname() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>GlassfishDB.SOSDefaultMessageProperty.MessagePropertyValue</code>.
     */
    public void setMessagepropertyvalue(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>GlassfishDB.SOSDefaultMessageProperty.MessagePropertyValue</code>.
     */
    public String getMessagepropertyvalue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SosdefaultmessagepropertyRecord
     */
    public SosdefaultmessagepropertyRecord() {
        super(Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY);
    }

    /**
     * Create a detached, initialised SosdefaultmessagepropertyRecord
     */
    public SosdefaultmessagepropertyRecord(String sosid, String messagepropertyname, String messagepropertyvalue) {
        super(Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY);

        setSosid(sosid);
        setMessagepropertyname(messagepropertyname);
        setMessagepropertyvalue(messagepropertyvalue);
        resetTouchedOnNotNull();
    }
}
