/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sos;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Sequence of Services
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SosRecord extends UpdatableRecordImpl<SosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.SOS.SOSID</code>.
     */
    public void setSosid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOS.SOSID</code>.
     */
    public String getSosid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.SOS.SOSName</code>.
     */
    public void setSosname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOS.SOSName</code>.
     */
    public String getSosname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.SOS.SOSDescription</code>.
     */
    public void setSosdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOS.SOSDescription</code>.
     */
    public String getSosdescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.SOS.ProcessID</code>.
     */
    public void setProcessid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.SOS.ProcessID</code>.
     */
    public String getProcessid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SosRecord
     */
    public SosRecord() {
        super(Sos.SOS);
    }

    /**
     * Create a detached, initialised SosRecord
     */
    public SosRecord(String sosid, String sosname, String sosdescription, String processid) {
        super(Sos.SOS);

        setSosid(sosid);
        setSosname(sosname);
        setSosdescription(sosdescription);
        setProcessid(processid);
        resetTouchedOnNotNull();
    }
}
