/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.User;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GlassfishDB.User.UserID</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GlassfishDB.User.UserID</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GlassfishDB.User.MandantID</code>.
     */
    public void setMandantid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>GlassfishDB.User.MandantID</code>.
     */
    public String getMandantid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>GlassfishDB.User.UserPassword</code>.
     */
    public void setUserpassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GlassfishDB.User.UserPassword</code>.
     */
    public String getUserpassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GlassfishDB.User.UserRole</code>.
     */
    public void setUserrole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>GlassfishDB.User.UserRole</code>.
     */
    public String getUserrole() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String userid, String mandantid, String userpassword, String userrole) {
        super(User.USER);

        setUserid(userid);
        setMandantid(mandantid);
        setUserpassword(userpassword);
        setUserrole(userrole);
        resetTouchedOnNotNull();
    }
}
