-- Messrunde 10c-4a -- Sitzung 0: Rahmen, Bestand, Vergleichsanker, Belegungsprobe
-- Auftrag:  "Prozessansicht -- freies Zeitfenster, Messrunde (Schritt 10c-4a)",
--           Stand 07.09.2026
-- Ergebnis: docs/process-view.md Paragraf 30 ff.
--
-- ERZEUGT von scripts/messung-prozessansicht-frei/erzeuge.py. Der Statementtext
-- kommt aus scripts/messung-prozessansicht/gerendert.txt (M116, aus
-- ProzessbaumRepository gefallen) und ist NUR in Ebene und Bereichspraedikat
-- variiert.
--
-- Ausschliesslich SELECT / SET / EXPLAIN. (Regel S1) Benutzer monitor_read.
-- G1: keine Zugangsdaten, kein Hostname. Mandanten-IDs sind Codes.
-- L9: SET max_statement_time = 60. Jedes Statement, das die Grenze reisst, ist
--     eine Abweichung vom Rahmen und wird als solche ausgewiesen.
--
-- Z1: Alle Fenster enden auf 2025-12-30 03:00:00 -- unterhalb des Dev-Ankers
--     2025-12-30 04:09:47, auf einer Stundengrenze, im dichten Bestand.
--
-- ZWECK. Drei Dinge, bevor gemessen wird:
--   1. Der Bestand der drei Ebenen -- sind es die Zahlen aus rollup.md?
--   2. Der Vergleichsanker: M116 NEXANS 48H (6,781 ms) und 12M (75,743 ms)
--      wiederholt. Eine Abweichung ueber 25 % wird ausgewiesen, nicht
--      weggerechnet -- dann ist diese Sitzung mit M116 nicht vergleichbar.
--   3. Die Belegungsprobe: je Fenster und Ebene COUNT(*) und SUM(anzahl),
--      mandantenfrei -- die Zeilenzahl, die der Bereichszugriff liest, und
--      gegen die die Laufzeiten normiert werden.

SELECT '=== 00 read_only (erste Abfrage der Sitzung) ===' AS marke;
SELECT @@global.read_only AS read_only, NOW() AS serverzeit, VERSION() AS version,
       @@max_statement_time AS grenze_vorher;

SET max_statement_time = 60;
SET profiling = 1;
SET profiling_history_size = 100;

SELECT '=== 01 Bestand der drei Ebenen ===' AS marke;
SELECT 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, MIN(stunde) AS erster, MAX(stunde) AS letzter FROM overlord_monitor.message_rollup
UNION ALL SELECT 'tag', COUNT(*), SUM(anzahl), MIN(tag), MAX(tag) FROM overlord_monitor.message_rollup_tag
UNION ALL SELECT 'monat', COUNT(*), SUM(anzahl), MIN(monat), MAX(monat) FROM overlord_monitor.message_rollup_monat;

SELECT '=== 02 Vergleichsanker: M116 wiederholt, Zeichen fuer Zeichen ===' AS marke;
SELECT '=== M116-REPRO-NEXANS-48H · Plan (Regel L15) ===' AS marke;
EXPLAIN select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
SELECT '=== M116-REPRO-NEXANS-48H · sechs Laeufe ===' AS marke;
SELECT MAX(QUERY_ID) INTO @basis FROM information_schema.PROFILING;
select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-28 05:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 05:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`;
SELECT 'M116-REPRO-NEXANS-48H' AS fall,
       COUNT(*)                          AS anzahl_laeufe,
       MAX(CASE WHEN rn = 1 THEN ms END) AS aufwaermlauf,
       MIN(CASE WHEN rn > 1 THEN ms END) AS beste_von_fuenf,
       GROUP_CONCAT(CASE WHEN rn > 1 THEN ms END ORDER BY rn) AS alle_fuenf
FROM (SELECT ROW_NUMBER() OVER (ORDER BY QUERY_ID) AS rn,
             ROUND(SUM(DURATION) * 1000, 3) AS ms
      FROM information_schema.PROFILING
      WHERE QUERY_ID > @basis + 1
      GROUP BY QUERY_ID) t;

SELECT '=== M116-REPRO-NEXANS-12M · Plan (Regel L15) ===' AS marke;
EXPLAIN select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
SELECT '=== M116-REPRO-NEXANS-12M · sechs Laeufe ===' AS marke;
SELECT MAX(QUERY_ID) INTO @basis FROM information_schema.PROFILING;
select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, sum(`overlord_monitor`.`message_rollup_monat`.`anzahl`) from `overlord_monitor`.`message_rollup_monat` where (`overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2026-01-01' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_monat`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`;
SELECT 'M116-REPRO-NEXANS-12M' AS fall,
       COUNT(*)                          AS anzahl_laeufe,
       MAX(CASE WHEN rn = 1 THEN ms END) AS aufwaermlauf,
       MIN(CASE WHEN rn > 1 THEN ms END) AS beste_von_fuenf,
       GROUP_CONCAT(CASE WHEN rn > 1 THEN ms END ORDER BY rn) AS alle_fuenf
FROM (SELECT ROW_NUMBER() OVER (ORDER BY QUERY_ID) AS rn,
             ROUND(SUM(DURATION) * 1000, 3) AS ms
      FROM information_schema.PROFILING
      WHERE QUERY_ID > @basis + 1
      GROUP BY QUERY_ID) t;

SELECT '=== 03 Belegungsprobe: die fuenf Spannen auf der Stundenebene (M147) ===' AS marke;
SELECT '24H' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2025-12-29 03:00:00' AND stunde < '2025-12-30 03:00:00'
UNION ALL
SELECT '7T' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2025-12-23 03:00:00' AND stunde < '2025-12-30 03:00:00'
UNION ALL
SELECT '30T' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2025-11-30 03:00:00' AND stunde < '2025-12-30 03:00:00'
UNION ALL
SELECT '90T' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2025-10-01 03:00:00' AND stunde < '2025-12-30 03:00:00'
UNION ALL
SELECT '365T' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2024-12-30 03:00:00' AND stunde < '2025-12-30 03:00:00';

SELECT '=== 04 Belegungsprobe: die fuenf Spannen auf der Tagesebene (M148) ===' AS marke;
SELECT '24H' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2025-12-29' AND tag < '2025-12-30'
UNION ALL
SELECT '7T' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2025-12-23' AND tag < '2025-12-30'
UNION ALL
SELECT '30T' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2025-11-30' AND tag < '2025-12-30'
UNION ALL
SELECT '90T' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2025-10-01' AND tag < '2025-12-30'
UNION ALL
SELECT '365T' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2024-12-30' AND tag < '2025-12-30';

SELECT '=== 05 Belegungsprobe: der Boesfall, fuenf Abschnitte und die ungeteilte Stundenlesung ===' AS marke;
SELECT '1 stunde_kopf' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2024-12-29 14:00:00' AND stunde < '2024-12-30 00:00:00'
UNION ALL
SELECT '2 tag_kopf' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2024-12-30' AND tag < '2025-01-01'
UNION ALL
SELECT '3 monat_mitte' AS fenster, 'monat' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT monat) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_monat WHERE monat >= '2025-01-01' AND monat < '2025-12-01'
UNION ALL
SELECT '4 tag_fuss' AS fenster, 'tag' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT tag) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup_tag WHERE tag >= '2025-12-01' AND tag < '2025-12-30'
UNION ALL
SELECT '5 stunde_fuss' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2025-12-30 00:00:00' AND stunde < '2025-12-30 03:00:00'
UNION ALL
SELECT 'E ungeteilt' AS fenster, 'stunde' AS ebene, COUNT(*) AS zeilen, SUM(anzahl) AS nachrichten, COUNT(DISTINCT stunde) AS eimer, COUNT(DISTINCT process_id) AS prozesse FROM overlord_monitor.message_rollup WHERE stunde >= '2024-12-29 14:00:00' AND stunde < '2025-12-30 03:00:00';

SELECT '=== 06 Ergebniszeilen je Mandant: 365T Stundenebene und Boesfall Z-U ===' AS marke;
SELECT 'NEXANS' AS mandant, '365T stunde' AS fall, COUNT(*) AS ergebniszeilen, SUM(summe) AS nachrichten FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) as `summe` from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`) x
UNION ALL SELECT 'NEXANS', 'boesfall Z-U', COUNT(*), SUM(summe) FROM (select `t`.`process_id`, `t`.`message_status`, sum(`t`.`anzahl`) as `summe` from (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` where exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS')) group by `t`.`process_id`, `t`.`message_status`) y;
SELECT 'VOTG' AS mandant, '365T stunde' AS fall, COUNT(*) AS ergebniszeilen, SUM(summe) AS nachrichten FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) as `summe` from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`) x
UNION ALL SELECT 'VOTG', 'boesfall Z-U', COUNT(*), SUM(summe) FROM (select `t`.`process_id`, `t`.`message_status`, sum(`t`.`anzahl`) as `summe` from (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` where exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG')) group by `t`.`process_id`, `t`.`message_status`) y;
SELECT 'IBIS' AS mandant, '365T stunde' AS fall, COUNT(*) AS ergebniszeilen, SUM(summe) AS nachrichten FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) as `summe` from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'IBIS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`) x
UNION ALL SELECT 'IBIS', 'boesfall Z-U', COUNT(*), SUM(summe) FROM (select `t`.`process_id`, `t`.`message_status`, sum(`t`.`anzahl`) as `summe` from (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` where exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'IBIS')) group by `t`.`process_id`, `t`.`message_status`) y;
SELECT 'SUTTONS' AS mandant, '365T stunde' AS fall, COUNT(*) AS ergebniszeilen, SUM(summe) AS nachrichten FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, sum(`overlord_monitor`.`message_rollup`.`anzahl`) as `summe` from `overlord_monitor`.`message_rollup` where (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS'))) group by `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`) x
UNION ALL SELECT 'SUTTONS', 'boesfall Z-U', COUNT(*), SUM(summe) FROM (select `t`.`process_id`, `t`.`message_status`, sum(`t`.`anzahl`) as `summe` from (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` where exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS')) group by `t`.`process_id`, `t`.`message_status`) y;

SELECT '=== 99 fertig ===' AS marke;
