-- Messrunde 10c-4a -- Sitzung 0b: Rollupzeilen je Mandant im Fenster
-- Auftrag:  "Prozessansicht -- freies Zeitfenster, Messrunde (Schritt 10c-4a)",
--           Stand 07.09.2026
-- Ergebnis: docs/process-view.md Paragraf 30 ff.
--
-- ERZEUGT von scripts/messung-prozessansicht-frei/erzeuge.py. Der Statementtext
-- kommt aus scripts/messung-prozessansicht/gerendert.txt (M116, aus
-- ProzessbaumRepository gefallen) und ist NUR in Ebene und Bereichspraedikat
-- variiert.
--
-- Ausschliesslich SELECT / SET / EXPLAIN. (Regel S1) Benutzer monitor_read.
-- G1: keine Zugangsdaten, kein Hostname. Mandanten-IDs sind Codes.
-- L9: SET max_statement_time = 60. Jedes Statement, das die Grenze reisst, ist
--     eine Abweichung vom Rahmen und wird als solche ausgewiesen.
--
-- Z1: Alle Fenster enden auf 2025-12-30 03:00:00 -- unterhalb des Dev-Ankers
--     2025-12-30 04:09:47, auf einer Stundengrenze, im dichten Bestand.
--
-- ZWECK. Wie viele Rollupzeilen gehoeren im 365T-Fenster (Stunde und Tag)
-- und in den fuenf Abschnitten des Boesfalls zum jeweiligen Mandanten?
-- Das ist die Zeilenzahl, die der mandantengetriebene Plan liest, und die
-- Zeilenzahl, die die Ableitung in Z-U nach der Mandantenkette behaelt.

SELECT '=== 00 read_only (erste Abfrage der Sitzung) ===' AS marke;
SELECT @@global.read_only AS read_only, NOW() AS serverzeit, VERSION() AS version,
       @@max_statement_time AS grenze_vorher;

SET max_statement_time = 60;
SET profiling = 1;
SET profiling_history_size = 100;

SELECT '=== 07 Rollupzeilen je Mandant: 365T Stunde, 365T Tag, Boesfall zerlegt ===' AS marke;
SELECT 'NEXANS' AS mandant, '365T stunde' AS fall, COUNT(*) AS rollupzeilen, SUM(anzahl) AS nachrichten FROM `overlord_monitor`.`message_rollup` WHERE `overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))
UNION ALL SELECT 'NEXANS', '365T tag', COUNT(*), SUM(anzahl) FROM `overlord_monitor`.`message_rollup_tag` WHERE `overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_tag`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'))
UNION ALL SELECT 'NEXANS', 'boesfall zerlegt', COUNT(*), SUM(`t`.`anzahl`) FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` WHERE exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'NEXANS'));
SELECT 'VOTG' AS mandant, '365T stunde' AS fall, COUNT(*) AS rollupzeilen, SUM(anzahl) AS nachrichten FROM `overlord_monitor`.`message_rollup` WHERE `overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG'))
UNION ALL SELECT 'VOTG', '365T tag', COUNT(*), SUM(anzahl) FROM `overlord_monitor`.`message_rollup_tag` WHERE `overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_tag`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG'))
UNION ALL SELECT 'VOTG', 'boesfall zerlegt', COUNT(*), SUM(`t`.`anzahl`) FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` WHERE exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'VOTG'));
SELECT 'IBIS' AS mandant, '365T stunde' AS fall, COUNT(*) AS rollupzeilen, SUM(anzahl) AS nachrichten FROM `overlord_monitor`.`message_rollup` WHERE `overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'IBIS'))
UNION ALL SELECT 'IBIS', '365T tag', COUNT(*), SUM(anzahl) FROM `overlord_monitor`.`message_rollup_tag` WHERE `overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_tag`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'IBIS'))
UNION ALL SELECT 'IBIS', 'boesfall zerlegt', COUNT(*), SUM(`t`.`anzahl`) FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` WHERE exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'IBIS'));
SELECT 'SUTTONS' AS mandant, '365T stunde' AS fall, COUNT(*) AS rollupzeilen, SUM(anzahl) AS nachrichten FROM `overlord_monitor`.`message_rollup` WHERE `overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-30 03:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS'))
UNION ALL SELECT 'SUTTONS', '365T tag', COUNT(*), SUM(anzahl) FROM `overlord_monitor`.`message_rollup_tag` WHERE `overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30' and exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `overlord_monitor`.`message_rollup_tag`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS'))
UNION ALL SELECT 'SUTTONS', 'boesfall zerlegt', COUNT(*), SUM(`t`.`anzahl`) FROM (select `overlord_monitor`.`message_rollup`.`process_id`, `overlord_monitor`.`message_rollup`.`message_status`, `overlord_monitor`.`message_rollup`.`anzahl` from `overlord_monitor`.`message_rollup` where ((`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2024-12-29 14:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2024-12-30 00:00:00.0') or (`overlord_monitor`.`message_rollup`.`stunde` >= timestamp '2025-12-30 00:00:00.0' and `overlord_monitor`.`message_rollup`.`stunde` < timestamp '2025-12-30 03:00:00.0')) union all select `overlord_monitor`.`message_rollup_tag`.`process_id`, `overlord_monitor`.`message_rollup_tag`.`message_status`, `overlord_monitor`.`message_rollup_tag`.`anzahl` from `overlord_monitor`.`message_rollup_tag` where ((`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2024-12-30' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-01-01') or (`overlord_monitor`.`message_rollup_tag`.`tag` >= date '2025-12-01' and `overlord_monitor`.`message_rollup_tag`.`tag` < date '2025-12-30')) union all select `overlord_monitor`.`message_rollup_monat`.`process_id`, `overlord_monitor`.`message_rollup_monat`.`message_status`, `overlord_monitor`.`message_rollup_monat`.`anzahl` from `overlord_monitor`.`message_rollup_monat` where `overlord_monitor`.`message_rollup_monat`.`monat` >= date '2025-01-01' and `overlord_monitor`.`message_rollup_monat`.`monat` < date '2025-12-01') as `t` WHERE exists (select 1 as `one` from `GlassfishDB`.`Process` as `baum_process` join `GlassfishDB`.`ProjectMandant` on `GlassfishDB`.`ProjectMandant`.`ProjectID` = `baum_process`.`ProjectID` where (`baum_process`.`ProcessID` = `t`.`process_id` and `GlassfishDB`.`ProjectMandant`.`MandantID` = 'SUTTONS'));

SELECT '=== 99 fertig ===' AS marke;
