/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUserMandant.AppUserMandantPath;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.AppUserRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUser extends TableImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.app_user</code>
     */
    public static final AppUser APP_USER = new AppUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserRecord> getRecordType() {
        return AppUserRecord.class;
    }

    /**
     * The column <code>overlord_monitor.app_user.id</code>.
     */
    public final TableField<AppUserRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>overlord_monitor.app_user.username</code>.
     */
    public final TableField<AppUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(190).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.app_user.password_hash</code>.
     */
    public final TableField<AppUserRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(60).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.role</code>.
     */
    public final TableField<AppUserRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.app_user.enabled</code>.
     */
    public final TableField<AppUserRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.must_change_password</code>.
     */
    public final TableField<AppUserRecord, Boolean> MUST_CHANGE_PASSWORD = createField(DSL.name("must_change_password"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.download_allowed</code>.
     */
    public final TableField<AppUserRecord, Boolean> DOWNLOAD_ALLOWED = createField(DSL.name("download_allowed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.failed_attempts</code>.
     */
    public final TableField<AppUserRecord, Integer> FAILED_ATTEMPTS = createField(DSL.name("failed_attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.locked_until</code>.
     */
    public final TableField<AppUserRecord, LocalDateTime> LOCKED_UNTIL = createField(DSL.name("locked_until"), SQLDataType.LOCALDATETIME(3).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.last_login_at</code>.
     */
    public final TableField<AppUserRecord, LocalDateTime> LAST_LOGIN_AT = createField(DSL.name("last_login_at"), SQLDataType.LOCALDATETIME(3).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>overlord_monitor.app_user.created_at</code>.
     */
    public final TableField<AppUserRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.app_user.updated_at</code>.
     */
    public final TableField<AppUserRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    private AppUser(Name alias, Table<AppUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppUser(Name alias, Table<AppUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.app_user</code> table reference
     */
    public AppUser(String alias) {
        this(DSL.name(alias), APP_USER);
    }

    /**
     * Create an aliased <code>overlord_monitor.app_user</code> table reference
     */
    public AppUser(Name alias) {
        this(alias, APP_USER);
    }

    /**
     * Create a <code>overlord_monitor.app_user</code> table reference
     */
    public AppUser() {
        this(DSL.name("app_user"), null);
    }

    public <O extends Record> AppUser(Table<O> path, ForeignKey<O, AppUserRecord> childPath, InverseForeignKey<O, AppUserRecord> parentPath) {
        super(path, childPath, parentPath, APP_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppUserPath extends AppUser implements Path<AppUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppUserPath(Table<O> path, ForeignKey<O, AppUserRecord> childPath, InverseForeignKey<O, AppUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppUserPath(Name alias, Table<AppUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppUserPath as(String alias) {
            return new AppUserPath(DSL.name(alias), this);
        }

        @Override
        public AppUserPath as(Name alias) {
            return new AppUserPath(alias, this);
        }

        @Override
        public AppUserPath as(Table<?> alias) {
            return new AppUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public Identity<AppUserRecord, Long> getIdentity() {
        return (Identity<AppUserRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AppUserRecord> getPrimaryKey() {
        return Keys.KEY_APP_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<AppUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_APP_USER_UQ_APP_USER_USERNAME);
    }

    private transient AppUserMandantPath _appUserMandant;

    /**
     * Get the implicit to-many join path to the
     * <code>overlord_monitor.app_user_mandant</code> table
     */
    public AppUserMandantPath appUserMandant() {
        if (_appUserMandant == null)
            _appUserMandant = new AppUserMandantPath(this, null, Keys.FK_APP_USER_MANDANT_USER.getInverseKey());

        return _appUserMandant;
    }

    @Override
    public AppUser as(String alias) {
        return new AppUser(DSL.name(alias), this);
    }

    @Override
    public AppUser as(Name alias) {
        return new AppUser(alias, this);
    }

    @Override
    public AppUser as(Table<?> alias) {
        return new AppUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUser rename(String name) {
        return new AppUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUser rename(Name name) {
        return new AppUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUser rename(Table<?> name) {
        return new AppUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUser where(Condition condition) {
        return new AppUser(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUser whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUser whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
