/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.AppUser.AppUserPath;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.AppUserMandantRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUserMandant extends TableImpl<AppUserMandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.app_user_mandant</code>
     */
    public static final AppUserMandant APP_USER_MANDANT = new AppUserMandant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppUserMandantRecord> getRecordType() {
        return AppUserMandantRecord.class;
    }

    /**
     * The column <code>overlord_monitor.app_user_mandant.user_id</code>.
     */
    public final TableField<AppUserMandantRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.app_user_mandant.mandant_id</code>.
     */
    public final TableField<AppUserMandantRecord, String> MANDANT_ID = createField(DSL.name("mandant_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private AppUserMandant(Name alias, Table<AppUserMandantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppUserMandant(Name alias, Table<AppUserMandantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.app_user_mandant</code> table
     * reference
     */
    public AppUserMandant(String alias) {
        this(DSL.name(alias), APP_USER_MANDANT);
    }

    /**
     * Create an aliased <code>overlord_monitor.app_user_mandant</code> table
     * reference
     */
    public AppUserMandant(Name alias) {
        this(alias, APP_USER_MANDANT);
    }

    /**
     * Create a <code>overlord_monitor.app_user_mandant</code> table reference
     */
    public AppUserMandant() {
        this(DSL.name("app_user_mandant"), null);
    }

    public <O extends Record> AppUserMandant(Table<O> path, ForeignKey<O, AppUserMandantRecord> childPath, InverseForeignKey<O, AppUserMandantRecord> parentPath) {
        super(path, childPath, parentPath, APP_USER_MANDANT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppUserMandantPath extends AppUserMandant implements Path<AppUserMandantRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppUserMandantPath(Table<O> path, ForeignKey<O, AppUserMandantRecord> childPath, InverseForeignKey<O, AppUserMandantRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppUserMandantPath(Name alias, Table<AppUserMandantRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppUserMandantPath as(String alias) {
            return new AppUserMandantPath(DSL.name(alias), this);
        }

        @Override
        public AppUserMandantPath as(Name alias) {
            return new AppUserMandantPath(alias, this);
        }

        @Override
        public AppUserMandantPath as(Table<?> alias) {
            return new AppUserMandantPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<AppUserMandantRecord> getPrimaryKey() {
        return Keys.KEY_APP_USER_MANDANT_PRIMARY;
    }

    @Override
    public List<ForeignKey<AppUserMandantRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_APP_USER_MANDANT_USER);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>overlord_monitor.app_user</code>
     * table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.FK_APP_USER_MANDANT_USER, null);

        return _appUser;
    }

    @Override
    public AppUserMandant as(String alias) {
        return new AppUserMandant(DSL.name(alias), this);
    }

    @Override
    public AppUserMandant as(Name alias) {
        return new AppUserMandant(alias, this);
    }

    @Override
    public AppUserMandant as(Table<?> alias) {
        return new AppUserMandant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserMandant rename(String name) {
        return new AppUserMandant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserMandant rename(Name name) {
        return new AppUserMandant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppUserMandant rename(Table<?> name) {
        return new AppUserMandant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserMandant where(Condition condition) {
        return new AppUserMandant(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserMandant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserMandant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserMandant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserMandant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserMandant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserMandant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppUserMandant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserMandant whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppUserMandant whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
