/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.AuditLogRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditLog extends TableImpl<AuditLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.audit_log</code>
     */
    public static final AuditLog AUDIT_LOG = new AuditLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditLogRecord> getRecordType() {
        return AuditLogRecord.class;
    }

    /**
     * The column <code>overlord_monitor.audit_log.id</code>.
     */
    public final TableField<AuditLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.occurred_at</code>.
     */
    public final TableField<AuditLogRecord, LocalDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.event_type</code>.
     */
    public final TableField<AuditLogRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.actor_user_id</code>.
     */
    public final TableField<AuditLogRecord, Long> ACTOR_USER_ID = createField(DSL.name("actor_user_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.actor_username</code>.
     */
    public final TableField<AuditLogRecord, String> ACTOR_USERNAME = createField(DSL.name("actor_username"), SQLDataType.VARCHAR(190).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.mandant_id</code>.
     */
    public final TableField<AuditLogRecord, String> MANDANT_ID = createField(DSL.name("mandant_id"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.target_type</code>.
     */
    public final TableField<AuditLogRecord, String> TARGET_TYPE = createField(DSL.name("target_type"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.target_id</code>.
     */
    public final TableField<AuditLogRecord, String> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.VARCHAR(190).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.ip</code>.
     */
    public final TableField<AuditLogRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.audit_log.detail</code>.
     */
    public final TableField<AuditLogRecord, String> DETAIL = createField(DSL.name("detail"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    private AuditLog(Name alias, Table<AuditLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuditLog(Name alias, Table<AuditLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.audit_log</code> table reference
     */
    public AuditLog(String alias) {
        this(DSL.name(alias), AUDIT_LOG);
    }

    /**
     * Create an aliased <code>overlord_monitor.audit_log</code> table reference
     */
    public AuditLog(Name alias) {
        this(alias, AUDIT_LOG);
    }

    /**
     * Create a <code>overlord_monitor.audit_log</code> table reference
     */
    public AuditLog() {
        this(DSL.name("audit_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUDIT_LOG_IDX_AUDIT_ACTOR, Indexes.AUDIT_LOG_IDX_AUDIT_OCCURRED, Indexes.AUDIT_LOG_IDX_AUDIT_TYPE);
    }

    @Override
    public Identity<AuditLogRecord, Long> getIdentity() {
        return (Identity<AuditLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuditLogRecord> getPrimaryKey() {
        return Keys.KEY_AUDIT_LOG_PRIMARY;
    }

    @Override
    public AuditLog as(String alias) {
        return new AuditLog(DSL.name(alias), this);
    }

    @Override
    public AuditLog as(Name alias) {
        return new AuditLog(alias, this);
    }

    @Override
    public AuditLog as(Table<?> alias) {
        return new AuditLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditLog rename(String name) {
        return new AuditLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditLog rename(Name name) {
        return new AuditLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditLog rename(Table<?> name) {
        return new AuditLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLog where(Condition condition) {
        return new AuditLog(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuditLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLog whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuditLog whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
