/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.BamSpalteRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BamSpalte extends TableImpl<BamSpalteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.bam_spalte</code>
     */
    public static final BamSpalte BAM_SPALTE = new BamSpalte();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BamSpalteRecord> getRecordType() {
        return BamSpalteRecord.class;
    }

    /**
     * The column <code>overlord_monitor.bam_spalte.mandant_id</code>.
     */
    public final TableField<BamSpalteRecord, String> MANDANT_ID = createField(DSL.name("mandant_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.bam_spalte.position</code>.
     */
    public final TableField<BamSpalteRecord, Byte> POSITION = createField(DSL.name("position"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.bam_spalte.message_bam_type</code>.
     */
    public final TableField<BamSpalteRecord, Short> MESSAGE_BAM_TYPE = createField(DSL.name("message_bam_type"), SQLDataType.SMALLINT.nullable(false), this, "");

    private BamSpalte(Name alias, Table<BamSpalteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BamSpalte(Name alias, Table<BamSpalteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.bam_spalte</code> table
     * reference
     */
    public BamSpalte(String alias) {
        this(DSL.name(alias), BAM_SPALTE);
    }

    /**
     * Create an aliased <code>overlord_monitor.bam_spalte</code> table
     * reference
     */
    public BamSpalte(Name alias) {
        this(alias, BAM_SPALTE);
    }

    /**
     * Create a <code>overlord_monitor.bam_spalte</code> table reference
     */
    public BamSpalte() {
        this(DSL.name("bam_spalte"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<BamSpalteRecord> getPrimaryKey() {
        return Keys.KEY_BAM_SPALTE_PRIMARY;
    }

    @Override
    public BamSpalte as(String alias) {
        return new BamSpalte(DSL.name(alias), this);
    }

    @Override
    public BamSpalte as(Name alias) {
        return new BamSpalte(alias, this);
    }

    @Override
    public BamSpalte as(Table<?> alias) {
        return new BamSpalte(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BamSpalte rename(String name) {
        return new BamSpalte(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BamSpalte rename(Name name) {
        return new BamSpalte(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BamSpalte rename(Table<?> name) {
        return new BamSpalte(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSpalte where(Condition condition) {
        return new BamSpalte(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSpalte where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSpalte where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSpalte where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSpalte where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSpalte where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSpalte where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSpalte where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSpalte whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSpalte whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
