/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.BamSollaengeRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BamSollaenge extends TableImpl<BamSollaengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.bam_sollaenge</code>
     */
    public static final BamSollaenge BAM_SOLLAENGE = new BamSollaenge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BamSollaengeRecord> getRecordType() {
        return BamSollaengeRecord.class;
    }

    /**
     * The column <code>overlord_monitor.bam_sollaenge.mandant_id</code>.
     */
    public final TableField<BamSollaengeRecord, String> MANDANT_ID = createField(DSL.name("mandant_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.bam_sollaenge.message_bam_type</code>.
     */
    public final TableField<BamSollaengeRecord, Short> MESSAGE_BAM_TYPE = createField(DSL.name("message_bam_type"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.bam_sollaenge.sollaenge</code>.
     */
    public final TableField<BamSollaengeRecord, UByte> SOLLAENGE = createField(DSL.name("sollaenge"), SQLDataType.TINYINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINTUNSIGNED)), this, "");

    /**
     * The column
     * <code>overlord_monitor.bam_sollaenge.fuehrendes_leerzeichen</code>.
     */
    public final TableField<BamSollaengeRecord, Boolean> FUEHRENDES_LEERZEICHEN = createField(DSL.name("fuehrendes_leerzeichen"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>overlord_monitor.bam_sollaenge.dominanz_prozent</code>.
     */
    public final TableField<BamSollaengeRecord, BigDecimal> DOMINANZ_PROZENT = createField(DSL.name("dominanz_prozent"), SQLDataType.DECIMAL(5, 2).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>overlord_monitor.bam_sollaenge.leerzeichen_prozent</code>.
     */
    public final TableField<BamSollaengeRecord, BigDecimal> LEERZEICHEN_PROZENT = createField(DSL.name("leerzeichen_prozent"), SQLDataType.DECIMAL(9, 6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>overlord_monitor.bam_sollaenge.zeilen</code>.
     */
    public final TableField<BamSollaengeRecord, Integer> ZEILEN = createField(DSL.name("zeilen"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.bam_sollaenge.gemessen_am</code>.
     */
    public final TableField<BamSollaengeRecord, LocalDate> GEMESSEN_AM = createField(DSL.name("gemessen_am"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private BamSollaenge(Name alias, Table<BamSollaengeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BamSollaenge(Name alias, Table<BamSollaengeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.bam_sollaenge</code> table
     * reference
     */
    public BamSollaenge(String alias) {
        this(DSL.name(alias), BAM_SOLLAENGE);
    }

    /**
     * Create an aliased <code>overlord_monitor.bam_sollaenge</code> table
     * reference
     */
    public BamSollaenge(Name alias) {
        this(alias, BAM_SOLLAENGE);
    }

    /**
     * Create a <code>overlord_monitor.bam_sollaenge</code> table reference
     */
    public BamSollaenge() {
        this(DSL.name("bam_sollaenge"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<BamSollaengeRecord> getPrimaryKey() {
        return Keys.KEY_BAM_SOLLAENGE_PRIMARY;
    }

    @Override
    public BamSollaenge as(String alias) {
        return new BamSollaenge(DSL.name(alias), this);
    }

    @Override
    public BamSollaenge as(Name alias) {
        return new BamSollaenge(alias, this);
    }

    @Override
    public BamSollaenge as(Table<?> alias) {
        return new BamSollaenge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BamSollaenge rename(String name) {
        return new BamSollaenge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BamSollaenge rename(Name name) {
        return new BamSollaenge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BamSollaenge rename(Table<?> name) {
        return new BamSollaenge(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSollaenge where(Condition condition) {
        return new BamSollaenge(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSollaenge where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSollaenge where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSollaenge where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSollaenge where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSollaenge where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSollaenge where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BamSollaenge where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSollaenge whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BamSollaenge whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
