/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.MessageRollupMonatRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRollupMonat extends TableImpl<MessageRollupMonatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>overlord_monitor.message_rollup_monat</code>
     */
    public static final MessageRollupMonat MESSAGE_ROLLUP_MONAT = new MessageRollupMonat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageRollupMonatRecord> getRecordType() {
        return MessageRollupMonatRecord.class;
    }

    /**
     * The column <code>overlord_monitor.message_rollup_monat.monat</code>.
     */
    public final TableField<MessageRollupMonatRecord, LocalDate> MONAT = createField(DSL.name("monat"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup_monat.process_id</code>.
     */
    public final TableField<MessageRollupMonatRecord, String> PROCESS_ID = createField(DSL.name("process_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column
     * <code>overlord_monitor.message_rollup_monat.message_status</code>.
     */
    public final TableField<MessageRollupMonatRecord, String> MESSAGE_STATUS = createField(DSL.name("message_status"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup_monat.anzahl</code>.
     */
    public final TableField<MessageRollupMonatRecord, Integer> ANZAHL = createField(DSL.name("anzahl"), SQLDataType.INTEGER.nullable(false), this, "");

    private MessageRollupMonat(Name alias, Table<MessageRollupMonatRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MessageRollupMonat(Name alias, Table<MessageRollupMonatRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.message_rollup_monat</code>
     * table reference
     */
    public MessageRollupMonat(String alias) {
        this(DSL.name(alias), MESSAGE_ROLLUP_MONAT);
    }

    /**
     * Create an aliased <code>overlord_monitor.message_rollup_monat</code>
     * table reference
     */
    public MessageRollupMonat(Name alias) {
        this(alias, MESSAGE_ROLLUP_MONAT);
    }

    /**
     * Create a <code>overlord_monitor.message_rollup_monat</code> table
     * reference
     */
    public MessageRollupMonat() {
        this(DSL.name("message_rollup_monat"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<MessageRollupMonatRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGE_ROLLUP_MONAT_PRIMARY;
    }

    @Override
    public MessageRollupMonat as(String alias) {
        return new MessageRollupMonat(DSL.name(alias), this);
    }

    @Override
    public MessageRollupMonat as(Name alias) {
        return new MessageRollupMonat(alias, this);
    }

    @Override
    public MessageRollupMonat as(Table<?> alias) {
        return new MessageRollupMonat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollupMonat rename(String name) {
        return new MessageRollupMonat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollupMonat rename(Name name) {
        return new MessageRollupMonat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollupMonat rename(Table<?> name) {
        return new MessageRollupMonat(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupMonat where(Condition condition) {
        return new MessageRollupMonat(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupMonat where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupMonat where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupMonat where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupMonat where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupMonat where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupMonat where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupMonat where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupMonat whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupMonat whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
