/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.MessageRollupTagRecord;

import java.time.LocalDate;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRollupTag extends TableImpl<MessageRollupTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>overlord_monitor.message_rollup_tag</code>
     */
    public static final MessageRollupTag MESSAGE_ROLLUP_TAG = new MessageRollupTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageRollupTagRecord> getRecordType() {
        return MessageRollupTagRecord.class;
    }

    /**
     * The column <code>overlord_monitor.message_rollup_tag.tag</code>.
     */
    public final TableField<MessageRollupTagRecord, LocalDate> TAG = createField(DSL.name("tag"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup_tag.process_id</code>.
     */
    public final TableField<MessageRollupTagRecord, String> PROCESS_ID = createField(DSL.name("process_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column
     * <code>overlord_monitor.message_rollup_tag.message_status</code>.
     */
    public final TableField<MessageRollupTagRecord, String> MESSAGE_STATUS = createField(DSL.name("message_status"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup_tag.anzahl</code>.
     */
    public final TableField<MessageRollupTagRecord, Integer> ANZAHL = createField(DSL.name("anzahl"), SQLDataType.INTEGER.nullable(false), this, "");

    private MessageRollupTag(Name alias, Table<MessageRollupTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MessageRollupTag(Name alias, Table<MessageRollupTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.message_rollup_tag</code> table
     * reference
     */
    public MessageRollupTag(String alias) {
        this(DSL.name(alias), MESSAGE_ROLLUP_TAG);
    }

    /**
     * Create an aliased <code>overlord_monitor.message_rollup_tag</code> table
     * reference
     */
    public MessageRollupTag(Name alias) {
        this(alias, MESSAGE_ROLLUP_TAG);
    }

    /**
     * Create a <code>overlord_monitor.message_rollup_tag</code> table reference
     */
    public MessageRollupTag() {
        this(DSL.name("message_rollup_tag"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<MessageRollupTagRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGE_ROLLUP_TAG_PRIMARY;
    }

    @Override
    public MessageRollupTag as(String alias) {
        return new MessageRollupTag(DSL.name(alias), this);
    }

    @Override
    public MessageRollupTag as(Name alias) {
        return new MessageRollupTag(alias, this);
    }

    @Override
    public MessageRollupTag as(Table<?> alias) {
        return new MessageRollupTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollupTag rename(String name) {
        return new MessageRollupTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollupTag rename(Name name) {
        return new MessageRollupTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollupTag rename(Table<?> name) {
        return new MessageRollupTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupTag where(Condition condition) {
        return new MessageRollupTag(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollupTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupTag whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollupTag whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
