/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.MessageRollupRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageRollup extends TableImpl<MessageRollupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.message_rollup</code>
     */
    public static final MessageRollup MESSAGE_ROLLUP = new MessageRollup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageRollupRecord> getRecordType() {
        return MessageRollupRecord.class;
    }

    /**
     * The column <code>overlord_monitor.message_rollup.stunde</code>.
     */
    public final TableField<MessageRollupRecord, LocalDateTime> STUNDE = createField(DSL.name("stunde"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup.process_id</code>.
     */
    public final TableField<MessageRollupRecord, String> PROCESS_ID = createField(DSL.name("process_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup.message_status</code>.
     */
    public final TableField<MessageRollupRecord, String> MESSAGE_STATUS = createField(DSL.name("message_status"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.message_rollup.anzahl</code>.
     */
    public final TableField<MessageRollupRecord, Integer> ANZAHL = createField(DSL.name("anzahl"), SQLDataType.INTEGER.nullable(false), this, "");

    private MessageRollup(Name alias, Table<MessageRollupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MessageRollup(Name alias, Table<MessageRollupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.message_rollup</code> table
     * reference
     */
    public MessageRollup(String alias) {
        this(DSL.name(alias), MESSAGE_ROLLUP);
    }

    /**
     * Create an aliased <code>overlord_monitor.message_rollup</code> table
     * reference
     */
    public MessageRollup(Name alias) {
        this(alias, MESSAGE_ROLLUP);
    }

    /**
     * Create a <code>overlord_monitor.message_rollup</code> table reference
     */
    public MessageRollup() {
        this(DSL.name("message_rollup"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<MessageRollupRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGE_ROLLUP_PRIMARY;
    }

    @Override
    public MessageRollup as(String alias) {
        return new MessageRollup(DSL.name(alias), this);
    }

    @Override
    public MessageRollup as(Name alias) {
        return new MessageRollup(alias, this);
    }

    @Override
    public MessageRollup as(Table<?> alias) {
        return new MessageRollup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollup rename(String name) {
        return new MessageRollup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollup rename(Name name) {
        return new MessageRollup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageRollup rename(Table<?> name) {
        return new MessageRollup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollup where(Condition condition) {
        return new MessageRollup(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageRollup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollup whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageRollup whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
