/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.ProcessCatalogRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessCatalog extends TableImpl<ProcessCatalogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.process_catalog</code>
     */
    public static final ProcessCatalog PROCESS_CATALOG = new ProcessCatalog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessCatalogRecord> getRecordType() {
        return ProcessCatalogRecord.class;
    }

    /**
     * The column <code>overlord_monitor.process_catalog.process_id</code>.
     */
    public final TableField<ProcessCatalogRecord, String> PROCESS_ID = createField(DSL.name("process_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.process_catalog.partner</code>.
     */
    public final TableField<ProcessCatalogRecord, String> PARTNER = createField(DSL.name("partner"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.process_catalog.richtung</code>.
     */
    public final TableField<ProcessCatalogRecord, String> RICHTUNG = createField(DSL.name("richtung"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>overlord_monitor.process_catalog.pflegestatus</code>.
     */
    public final TableField<ProcessCatalogRecord, String> PFLEGESTATUS = createField(DSL.name("pflegestatus"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column
     * <code>overlord_monitor.process_catalog.vorschlag_herkunft</code>.
     */
    public final TableField<ProcessCatalogRecord, String> VORSCHLAG_HERKUNFT = createField(DSL.name("vorschlag_herkunft"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.process_catalog.geaendert_am</code>.
     */
    public final TableField<ProcessCatalogRecord, LocalDateTime> GEAENDERT_AM = createField(DSL.name("geaendert_am"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.process_catalog.geaendert_von</code>.
     */
    public final TableField<ProcessCatalogRecord, String> GEAENDERT_VON = createField(DSL.name("geaendert_von"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private ProcessCatalog(Name alias, Table<ProcessCatalogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcessCatalog(Name alias, Table<ProcessCatalogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.process_catalog</code> table
     * reference
     */
    public ProcessCatalog(String alias) {
        this(DSL.name(alias), PROCESS_CATALOG);
    }

    /**
     * Create an aliased <code>overlord_monitor.process_catalog</code> table
     * reference
     */
    public ProcessCatalog(Name alias) {
        this(alias, PROCESS_CATALOG);
    }

    /**
     * Create a <code>overlord_monitor.process_catalog</code> table reference
     */
    public ProcessCatalog() {
        this(DSL.name("process_catalog"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public UniqueKey<ProcessCatalogRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_CATALOG_PRIMARY;
    }

    @Override
    public ProcessCatalog as(String alias) {
        return new ProcessCatalog(DSL.name(alias), this);
    }

    @Override
    public ProcessCatalog as(Name alias) {
        return new ProcessCatalog(alias, this);
    }

    @Override
    public ProcessCatalog as(Table<?> alias) {
        return new ProcessCatalog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessCatalog rename(String name) {
        return new ProcessCatalog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessCatalog rename(Name name) {
        return new ProcessCatalog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessCatalog rename(Table<?> name) {
        return new ProcessCatalog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessCatalog where(Condition condition) {
        return new ProcessCatalog(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessCatalog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessCatalog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessCatalog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessCatalog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessCatalog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessCatalog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessCatalog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessCatalog whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessCatalog whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
