/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.monitor.tables;


import de.kraftwerkone.overlord.monitor.jooq.monitor.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.monitor.Keys;
import de.kraftwerkone.overlord.monitor.jooq.monitor.OverlordMonitor;
import de.kraftwerkone.overlord.monitor.jooq.monitor.tables.records.RollupLaufRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RollupLauf extends TableImpl<RollupLaufRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>overlord_monitor.rollup_lauf</code>
     */
    public static final RollupLauf ROLLUP_LAUF = new RollupLauf();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RollupLaufRecord> getRecordType() {
        return RollupLaufRecord.class;
    }

    /**
     * The column <code>overlord_monitor.rollup_lauf.id</code>.
     */
    public final TableField<RollupLaufRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.art</code>.
     */
    public final TableField<RollupLaufRecord, String> ART = createField(DSL.name("art"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.fenster_von</code>.
     */
    public final TableField<RollupLaufRecord, LocalDateTime> FENSTER_VON = createField(DSL.name("fenster_von"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.fenster_bis</code>.
     */
    public final TableField<RollupLaufRecord, LocalDateTime> FENSTER_BIS = createField(DSL.name("fenster_bis"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.gestartet_am</code>.
     */
    public final TableField<RollupLaufRecord, LocalDateTime> GESTARTET_AM = createField(DSL.name("gestartet_am"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.beendet_am</code>.
     */
    public final TableField<RollupLaufRecord, LocalDateTime> BEENDET_AM = createField(DSL.name("beendet_am"), SQLDataType.LOCALDATETIME(3).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.zeilen_geschrieben</code>.
     */
    public final TableField<RollupLaufRecord, Integer> ZEILEN_GESCHRIEBEN = createField(DSL.name("zeilen_geschrieben"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>overlord_monitor.rollup_lauf.fehler</code>.
     */
    public final TableField<RollupLaufRecord, String> FEHLER = createField(DSL.name("fehler"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    private RollupLauf(Name alias, Table<RollupLaufRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RollupLauf(Name alias, Table<RollupLaufRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>overlord_monitor.rollup_lauf</code> table
     * reference
     */
    public RollupLauf(String alias) {
        this(DSL.name(alias), ROLLUP_LAUF);
    }

    /**
     * Create an aliased <code>overlord_monitor.rollup_lauf</code> table
     * reference
     */
    public RollupLauf(Name alias) {
        this(alias, ROLLUP_LAUF);
    }

    /**
     * Create a <code>overlord_monitor.rollup_lauf</code> table reference
     */
    public RollupLauf() {
        this(DSL.name("rollup_lauf"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : OverlordMonitor.OVERLORD_MONITOR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROLLUP_LAUF_ROLLUP_LAUF_STAND_IDX);
    }

    @Override
    public Identity<RollupLaufRecord, Long> getIdentity() {
        return (Identity<RollupLaufRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RollupLaufRecord> getPrimaryKey() {
        return Keys.KEY_ROLLUP_LAUF_PRIMARY;
    }

    @Override
    public RollupLauf as(String alias) {
        return new RollupLauf(DSL.name(alias), this);
    }

    @Override
    public RollupLauf as(Name alias) {
        return new RollupLauf(alias, this);
    }

    @Override
    public RollupLauf as(Table<?> alias) {
        return new RollupLauf(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RollupLauf rename(String name) {
        return new RollupLauf(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RollupLauf rename(Name name) {
        return new RollupLauf(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RollupLauf rename(Table<?> name) {
        return new RollupLauf(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RollupLauf where(Condition condition) {
        return new RollupLauf(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RollupLauf where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RollupLauf where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RollupLauf where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RollupLauf where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RollupLauf where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RollupLauf where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RollupLauf where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RollupLauf whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RollupLauf whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
