/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MandantRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Mandant extends TableImpl<MandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.Mandant</code>
     */
    public static final Mandant MANDANT = new Mandant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MandantRecord> getRecordType() {
        return MandantRecord.class;
    }

    /**
     * The column <code>GlassfishDB.Mandant.MandantID</code>.
     */
    public final TableField<MandantRecord, String> MANDANTID = createField(DSL.name("MandantID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.Mandant.MandantName</code>.
     */
    public final TableField<MandantRecord, String> MANDANTNAME = createField(DSL.name("MandantName"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Mandant.MandantDescription</code>.
     */
    public final TableField<MandantRecord, String> MANDANTDESCRIPTION = createField(DSL.name("MandantDescription"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    private Mandant(Name alias, Table<MandantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Mandant(Name alias, Table<MandantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.Mandant</code> table reference
     */
    public Mandant(String alias) {
        this(DSL.name(alias), MANDANT);
    }

    /**
     * Create an aliased <code>GlassfishDB.Mandant</code> table reference
     */
    public Mandant(Name alias) {
        this(alias, MANDANT);
    }

    /**
     * Create a <code>GlassfishDB.Mandant</code> table reference
     */
    public Mandant() {
        this(DSL.name("Mandant"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MANDANT_PRIMARY);
    }

    @Override
    public UniqueKey<MandantRecord> getPrimaryKey() {
        return Keys.KEY_MANDANT_PRIMARY;
    }

    @Override
    public Mandant as(String alias) {
        return new Mandant(DSL.name(alias), this);
    }

    @Override
    public Mandant as(Name alias) {
        return new Mandant(alias, this);
    }

    @Override
    public Mandant as(Table<?> alias) {
        return new Mandant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mandant rename(String name) {
        return new Mandant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mandant rename(Name name) {
        return new Mandant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mandant rename(Table<?> name) {
        return new Mandant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mandant where(Condition condition) {
        return new Mandant(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mandant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mandant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mandant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mandant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mandant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mandant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Mandant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mandant whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Mandant whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
