/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagestatistichistoryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagestatistichistory extends TableImpl<MessagestatistichistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>GlassfishDB.MessageStatisticHistory</code>
     */
    public static final Messagestatistichistory MESSAGESTATISTICHISTORY = new Messagestatistichistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagestatistichistoryRecord> getRecordType() {
        return MessagestatistichistoryRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageStatisticHistory.Period</code>.
     */
    public final TableField<MessagestatistichistoryRecord, String> PERIOD = createField(DSL.name("Period"), SQLDataType.VARCHAR(54).nullable(false), this, "");

    /**
     * The column
     * <code>GlassfishDB.MessageStatisticHistory.NumberOfMessages</code>.
     */
    public final TableField<MessagestatistichistoryRecord, Long> NUMBEROFMESSAGES = createField(DSL.name("NumberOfMessages"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private Messagestatistichistory(Name alias, Table<MessagestatistichistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagestatistichistory(Name alias, Table<MessagestatistichistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageStatisticHistory</code> table
     * reference
     */
    public Messagestatistichistory(String alias) {
        this(DSL.name(alias), MESSAGESTATISTICHISTORY);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageStatisticHistory</code> table
     * reference
     */
    public Messagestatistichistory(Name alias) {
        this(alias, MESSAGESTATISTICHISTORY);
    }

    /**
     * Create a <code>GlassfishDB.MessageStatisticHistory</code> table reference
     */
    public Messagestatistichistory() {
        this(DSL.name("MessageStatisticHistory"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGESTATISTICHISTORY_PRIMARY);
    }

    @Override
    public UniqueKey<MessagestatistichistoryRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGESTATISTICHISTORY_PRIMARY;
    }

    @Override
    public Messagestatistichistory as(String alias) {
        return new Messagestatistichistory(DSL.name(alias), this);
    }

    @Override
    public Messagestatistichistory as(Name alias) {
        return new Messagestatistichistory(alias, this);
    }

    @Override
    public Messagestatistichistory as(Table<?> alias) {
        return new Messagestatistichistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagestatistichistory rename(String name) {
        return new Messagestatistichistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagestatistichistory rename(Name name) {
        return new Messagestatistichistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagestatistichistory rename(Table<?> name) {
        return new Messagestatistichistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistichistory where(Condition condition) {
        return new Messagestatistichistory(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistichistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistichistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistichistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistichistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistichistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistichistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistichistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistichistory whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistichistory whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
