/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagebamRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagebam extends TableImpl<MessagebamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageBAM</code>
     */
    public static final Messagebam MESSAGEBAM = new Messagebam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagebamRecord> getRecordType() {
        return MessagebamRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageBAM.MessageID</code>.
     */
    public final TableField<MessagebamRecord, String> MESSAGEID = createField(DSL.name("MessageID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageBAM.MessageBAMType</code>.
     */
    public final TableField<MessagebamRecord, Short> MESSAGEBAMTYPE = createField(DSL.name("MessageBAMType"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageBAM.MessageBAMValue</code>.
     */
    public final TableField<MessagebamRecord, String> MESSAGEBAMVALUE = createField(DSL.name("MessageBAMValue"), SQLDataType.VARCHAR(70).nullable(false), this, "");

    private Messagebam(Name alias, Table<MessagebamRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagebam(Name alias, Table<MessagebamRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageBAM</code> table reference
     */
    public Messagebam(String alias) {
        this(DSL.name(alias), MESSAGEBAM);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageBAM</code> table reference
     */
    public Messagebam(Name alias) {
        this(alias, MESSAGEBAM);
    }

    /**
     * Create a <code>GlassfishDB.MessageBAM</code> table reference
     */
    public Messagebam() {
        this(DSL.name("MessageBAM"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGEBAM_MESSAGEBAM_BAMVALUE, Indexes.MESSAGEBAM_MESSAGEBAM_BAMVALUEONLY, Indexes.MESSAGEBAM_MESSAGEBAM_MESSAGEFK, Indexes.MESSAGEBAM_MESSAGEBAM_MESSAGEID, Indexes.MESSAGEBAM_PRIMARY);
    }

    @Override
    public UniqueKey<MessagebamRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGEBAM_PRIMARY;
    }

    @Override
    public Messagebam as(String alias) {
        return new Messagebam(DSL.name(alias), this);
    }

    @Override
    public Messagebam as(Name alias) {
        return new Messagebam(alias, this);
    }

    @Override
    public Messagebam as(Table<?> alias) {
        return new Messagebam(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebam rename(String name) {
        return new Messagebam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebam rename(Name name) {
        return new Messagebam(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebam rename(Table<?> name) {
        return new Messagebam(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebam where(Condition condition) {
        return new Messagebam(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebam where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebam where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebam where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebam where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebam where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebam where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebam where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebam whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebam whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
