/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagepropertysearchlistentryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagepropertysearchlistentry extends TableImpl<MessagepropertysearchlistentryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>GlassfishDB.MessagePropertySearchListEntry</code>
     */
    public static final Messagepropertysearchlistentry MESSAGEPROPERTYSEARCHLISTENTRY = new Messagepropertysearchlistentry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagepropertysearchlistentryRecord> getRecordType() {
        return MessagepropertysearchlistentryRecord.class;
    }

    /**
     * The column
     * <code>GlassfishDB.MessagePropertySearchListEntry.MessagePropertyName</code>.
     */
    public final TableField<MessagepropertysearchlistentryRecord, String> MESSAGEPROPERTYNAME = createField(DSL.name("MessagePropertyName"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column
     * <code>GlassfishDB.MessagePropertySearchListEntry.MandantID</code>.
     */
    public final TableField<MessagepropertysearchlistentryRecord, String> MANDANTID = createField(DSL.name("MandantID"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Messagepropertysearchlistentry(Name alias, Table<MessagepropertysearchlistentryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagepropertysearchlistentry(Name alias, Table<MessagepropertysearchlistentryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessagePropertySearchListEntry</code>
     * table reference
     */
    public Messagepropertysearchlistentry(String alias) {
        this(DSL.name(alias), MESSAGEPROPERTYSEARCHLISTENTRY);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessagePropertySearchListEntry</code>
     * table reference
     */
    public Messagepropertysearchlistentry(Name alias) {
        this(alias, MESSAGEPROPERTYSEARCHLISTENTRY);
    }

    /**
     * Create a <code>GlassfishDB.MessagePropertySearchListEntry</code> table
     * reference
     */
    public Messagepropertysearchlistentry() {
        this(DSL.name("MessagePropertySearchListEntry"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGEPROPERTYSEARCHLISTENTRY_PRIMARY);
    }

    @Override
    public UniqueKey<MessagepropertysearchlistentryRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGEPROPERTYSEARCHLISTENTRY_PRIMARY;
    }

    @Override
    public Messagepropertysearchlistentry as(String alias) {
        return new Messagepropertysearchlistentry(DSL.name(alias), this);
    }

    @Override
    public Messagepropertysearchlistentry as(Name alias) {
        return new Messagepropertysearchlistentry(alias, this);
    }

    @Override
    public Messagepropertysearchlistentry as(Table<?> alias) {
        return new Messagepropertysearchlistentry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagepropertysearchlistentry rename(String name) {
        return new Messagepropertysearchlistentry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagepropertysearchlistentry rename(Name name) {
        return new Messagepropertysearchlistentry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagepropertysearchlistentry rename(Table<?> name) {
        return new Messagepropertysearchlistentry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagepropertysearchlistentry where(Condition condition) {
        return new Messagepropertysearchlistentry(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagepropertysearchlistentry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagepropertysearchlistentry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagepropertysearchlistentry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagepropertysearchlistentry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagepropertysearchlistentry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagepropertysearchlistentry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagepropertysearchlistentry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagepropertysearchlistentry whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagepropertysearchlistentry whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
