/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessageactionRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messageaction extends TableImpl<MessageactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageAction</code>
     */
    public static final Messageaction MESSAGEACTION = new Messageaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageactionRecord> getRecordType() {
        return MessageactionRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageAction.MessageID</code>.
     */
    public final TableField<MessageactionRecord, String> MESSAGEID = createField(DSL.name("MessageID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.MessageActionID</code>.
     */
    public final TableField<MessageactionRecord, Short> MESSAGEACTIONID = createField(DSL.name("MessageActionID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.SOSID</code>.
     */
    public final TableField<MessageactionRecord, String> SOSID = createField(DSL.name("SOSID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.SOSActionID</code>.
     */
    public final TableField<MessageactionRecord, Short> SOSACTIONID = createField(DSL.name("SOSActionID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.MessageActionStart</code>.
     */
    public final TableField<MessageactionRecord, LocalDateTime> MESSAGEACTIONSTART = createField(DSL.name("MessageActionStart"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.MessageActionEnd</code>.
     */
    public final TableField<MessageactionRecord, LocalDateTime> MESSAGEACTIONEND = createField(DSL.name("MessageActionEnd"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.ServiceID</code>.
     */
    public final TableField<MessageactionRecord, String> SERVICEID = createField(DSL.name("ServiceID"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>GlassfishDB.MessageAction.SOSActionServiceProperties</code>.
     */
    public final TableField<MessageactionRecord, String> SOSACTIONSERVICEPROPERTIES = createField(DSL.name("SOSActionServiceProperties"), SQLDataType.CLOB(16777215).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.MessageAction.SOSActionTimeout</code>.
     */
    public final TableField<MessageactionRecord, Short> SOSACTIONTIMEOUT = createField(DSL.name("SOSActionTimeout"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.SMALLINT)), this, "");

    private Messageaction(Name alias, Table<MessageactionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messageaction(Name alias, Table<MessageactionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageAction</code> table reference
     */
    public Messageaction(String alias) {
        this(DSL.name(alias), MESSAGEACTION);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageAction</code> table reference
     */
    public Messageaction(Name alias) {
        this(alias, MESSAGEACTION);
    }

    /**
     * Create a <code>GlassfishDB.MessageAction</code> table reference
     */
    public Messageaction() {
        this(DSL.name("MessageAction"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGEACTION_MESSAGEACTION_MESSAGEFK, Indexes.MESSAGEACTION_PRIMARY);
    }

    @Override
    public UniqueKey<MessageactionRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGEACTION_PRIMARY;
    }

    @Override
    public Messageaction as(String alias) {
        return new Messageaction(DSL.name(alias), this);
    }

    @Override
    public Messageaction as(Name alias) {
        return new Messageaction(alias, this);
    }

    @Override
    public Messageaction as(Table<?> alias) {
        return new Messageaction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messageaction rename(String name) {
        return new Messageaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messageaction rename(Name name) {
        return new Messageaction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messageaction rename(Table<?> name) {
        return new Messageaction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageaction where(Condition condition) {
        return new Messageaction(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageaction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageaction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageaction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageaction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageaction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageaction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageaction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageaction whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageaction whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
