/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagebamtypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagebamtype extends TableImpl<MessagebamtypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageBAMType</code>
     */
    public static final Messagebamtype MESSAGEBAMTYPE = new Messagebamtype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagebamtypeRecord> getRecordType() {
        return MessagebamtypeRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageBAMType.MessageBAMType</code>.
     */
    public final TableField<MessagebamtypeRecord, Short> MESSAGEBAMTYPE_ = createField(DSL.name("MessageBAMType"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column
     * <code>GlassfishDB.MessageBAMType.MessageBAMTypeDescription</code>.
     */
    public final TableField<MessagebamtypeRecord, String> MESSAGEBAMTYPEDESCRIPTION = createField(DSL.name("MessageBAMTypeDescription"), SQLDataType.VARCHAR(70).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Messagebamtype(Name alias, Table<MessagebamtypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagebamtype(Name alias, Table<MessagebamtypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageBAMType</code> table reference
     */
    public Messagebamtype(String alias) {
        this(DSL.name(alias), MESSAGEBAMTYPE);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageBAMType</code> table reference
     */
    public Messagebamtype(Name alias) {
        this(alias, MESSAGEBAMTYPE);
    }

    /**
     * Create a <code>GlassfishDB.MessageBAMType</code> table reference
     */
    public Messagebamtype() {
        this(DSL.name("MessageBAMType"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGEBAMTYPE_PRIMARY);
    }

    @Override
    public UniqueKey<MessagebamtypeRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGEBAMTYPE_PRIMARY;
    }

    @Override
    public Messagebamtype as(String alias) {
        return new Messagebamtype(DSL.name(alias), this);
    }

    @Override
    public Messagebamtype as(Name alias) {
        return new Messagebamtype(alias, this);
    }

    @Override
    public Messagebamtype as(Table<?> alias) {
        return new Messagebamtype(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebamtype rename(String name) {
        return new Messagebamtype(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebamtype rename(Name name) {
        return new Messagebamtype(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebamtype rename(Table<?> name) {
        return new Messagebamtype(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebamtype where(Condition condition) {
        return new Messagebamtype(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebamtype where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebamtype where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebamtype where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebamtype where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebamtype where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebamtype where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebamtype where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebamtype whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebamtype whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
