/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagebammandantRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagebammandant extends TableImpl<MessagebammandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageBAMMandant</code>
     */
    public static final Messagebammandant MESSAGEBAMMANDANT = new Messagebammandant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagebammandantRecord> getRecordType() {
        return MessagebammandantRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageBAMMandant.MessageBAMType</code>.
     */
    public final TableField<MessagebammandantRecord, Short> MESSAGEBAMTYPE = createField(DSL.name("MessageBAMType"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageBAMMandant.MandantID</code>.
     */
    public final TableField<MessagebammandantRecord, String> MANDANTID = createField(DSL.name("MandantID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column
     * <code>GlassfishDB.MessageBAMMandant.MessageBAMTypeSortIndex</code>.
     */
    public final TableField<MessagebammandantRecord, Short> MESSAGEBAMTYPESORTINDEX = createField(DSL.name("MessageBAMTypeSortIndex"), SQLDataType.SMALLINT.nullable(false), this, "");

    private Messagebammandant(Name alias, Table<MessagebammandantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagebammandant(Name alias, Table<MessagebammandantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageBAMMandant</code> table
     * reference
     */
    public Messagebammandant(String alias) {
        this(DSL.name(alias), MESSAGEBAMMANDANT);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageBAMMandant</code> table
     * reference
     */
    public Messagebammandant(Name alias) {
        this(alias, MESSAGEBAMMANDANT);
    }

    /**
     * Create a <code>GlassfishDB.MessageBAMMandant</code> table reference
     */
    public Messagebammandant() {
        this(DSL.name("MessageBAMMandant"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGEBAMMANDANT_MANDANTIDSORTINDEXBAMTYPEIDX, Indexes.MESSAGEBAMMANDANT_PRIMARY);
    }

    @Override
    public UniqueKey<MessagebammandantRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGEBAMMANDANT_PRIMARY;
    }

    @Override
    public Messagebammandant as(String alias) {
        return new Messagebammandant(DSL.name(alias), this);
    }

    @Override
    public Messagebammandant as(Name alias) {
        return new Messagebammandant(alias, this);
    }

    @Override
    public Messagebammandant as(Table<?> alias) {
        return new Messagebammandant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebammandant rename(String name) {
        return new Messagebammandant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebammandant rename(Name name) {
        return new Messagebammandant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagebammandant rename(Table<?> name) {
        return new Messagebammandant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebammandant where(Condition condition) {
        return new Messagebammandant(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebammandant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebammandant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebammandant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebammandant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebammandant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebammandant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagebammandant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebammandant whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagebammandant whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
