/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagestatisticRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagestatistic extends TableImpl<MessagestatisticRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageStatistic</code>
     */
    public static final Messagestatistic MESSAGESTATISTIC = new Messagestatistic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagestatisticRecord> getRecordType() {
        return MessagestatisticRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageStatistic.Period</code>.
     */
    public final TableField<MessagestatisticRecord, String> PERIOD = createField(DSL.name("Period"), SQLDataType.VARCHAR(54).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.MessageStatistic.NumberOfMessages</code>.
     */
    public final TableField<MessagestatisticRecord, Long> NUMBEROFMESSAGES = createField(DSL.name("NumberOfMessages"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private Messagestatistic(Name alias, Table<MessagestatisticRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagestatistic(Name alias, Table<MessagestatisticRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW `MessageStatistic` AS "), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageStatistic</code> table
     * reference
     */
    public Messagestatistic(String alias) {
        this(DSL.name(alias), MESSAGESTATISTIC);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageStatistic</code> table
     * reference
     */
    public Messagestatistic(Name alias) {
        this(alias, MESSAGESTATISTIC);
    }

    /**
     * Create a <code>GlassfishDB.MessageStatistic</code> table reference
     */
    public Messagestatistic() {
        this(DSL.name("MessageStatistic"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public Messagestatistic as(String alias) {
        return new Messagestatistic(DSL.name(alias), this);
    }

    @Override
    public Messagestatistic as(Name alias) {
        return new Messagestatistic(alias, this);
    }

    @Override
    public Messagestatistic as(Table<?> alias) {
        return new Messagestatistic(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagestatistic rename(String name) {
        return new Messagestatistic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagestatistic rename(Name name) {
        return new Messagestatistic(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagestatistic rename(Table<?> name) {
        return new Messagestatistic(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistic where(Condition condition) {
        return new Messagestatistic(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistic where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistic where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistic where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistic where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistic where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistic where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagestatistic where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistic whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagestatistic whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
