/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagepropertyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messageproperty extends TableImpl<MessagepropertyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageProperty</code>
     */
    public static final Messageproperty MESSAGEPROPERTY = new Messageproperty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagepropertyRecord> getRecordType() {
        return MessagepropertyRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageProperty.MessageID</code>.
     */
    public final TableField<MessagepropertyRecord, String> MESSAGEID = createField(DSL.name("MessageID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageProperty.MessageActionID</code>.
     */
    public final TableField<MessagepropertyRecord, Short> MESSAGEACTIONID = createField(DSL.name("MessageActionID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageProperty.MessagePropertyName</code>.
     */
    public final TableField<MessagepropertyRecord, String> MESSAGEPROPERTYNAME = createField(DSL.name("MessagePropertyName"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageProperty.MessagePropertyValue</code>.
     */
    public final TableField<MessagepropertyRecord, String> MESSAGEPROPERTYVALUE = createField(DSL.name("MessagePropertyValue"), SQLDataType.CLOB(16777215).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    private Messageproperty(Name alias, Table<MessagepropertyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messageproperty(Name alias, Table<MessagepropertyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageProperty</code> table
     * reference
     */
    public Messageproperty(String alias) {
        this(DSL.name(alias), MESSAGEPROPERTY);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageProperty</code> table
     * reference
     */
    public Messageproperty(Name alias) {
        this(alias, MESSAGEPROPERTY);
    }

    /**
     * Create a <code>GlassfishDB.MessageProperty</code> table reference
     */
    public Messageproperty() {
        this(DSL.name("MessageProperty"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MESSAGEPROPERTY_MESSAGEPROPERTY_MESSAGEACTIONFK, Indexes.MESSAGEPROPERTY_MESSAGEPROPERTY_MESSAGEFK, Indexes.MESSAGEPROPERTY_MESSAGEPROPERTYNAMEIDX, Indexes.MESSAGEPROPERTY_MESSAGEPROPERTYNAMEVALUEIDX, Indexes.MESSAGEPROPERTY_MESSAGEPROPERTYVALUEIDX, Indexes.MESSAGEPROPERTY_PRIMARY);
    }

    @Override
    public UniqueKey<MessagepropertyRecord> getPrimaryKey() {
        return Keys.KEY_MESSAGEPROPERTY_PRIMARY;
    }

    @Override
    public Messageproperty as(String alias) {
        return new Messageproperty(DSL.name(alias), this);
    }

    @Override
    public Messageproperty as(Name alias) {
        return new Messageproperty(alias, this);
    }

    @Override
    public Messageproperty as(Table<?> alias) {
        return new Messageproperty(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messageproperty rename(String name) {
        return new Messageproperty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messageproperty rename(Name name) {
        return new Messageproperty(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messageproperty rename(Table<?> name) {
        return new Messageproperty(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageproperty where(Condition condition) {
        return new Messageproperty(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageproperty where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageproperty where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageproperty where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageproperty where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageproperty where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageproperty where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messageproperty where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageproperty whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messageproperty whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
