/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagemandantidRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Messagemandantid extends TableImpl<MessagemandantidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.MessageMandantID</code>
     */
    public static final Messagemandantid MESSAGEMANDANTID = new Messagemandantid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessagemandantidRecord> getRecordType() {
        return MessagemandantidRecord.class;
    }

    /**
     * The column <code>GlassfishDB.MessageMandantID.MessageID</code>.
     */
    public final TableField<MessagemandantidRecord, String> MESSAGEID = createField(DSL.name("MessageID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.MessageMandantID.MandantID</code>.
     */
    public final TableField<MessagemandantidRecord, String> MANDANTID = createField(DSL.name("MandantID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private Messagemandantid(Name alias, Table<MessagemandantidRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Messagemandantid(Name alias, Table<MessagemandantidRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("CREATE VIEW `MessageMandantID` AS "), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageMandantID</code> table
     * reference
     */
    public Messagemandantid(String alias) {
        this(DSL.name(alias), MESSAGEMANDANTID);
    }

    /**
     * Create an aliased <code>GlassfishDB.MessageMandantID</code> table
     * reference
     */
    public Messagemandantid(Name alias) {
        this(alias, MESSAGEMANDANTID);
    }

    /**
     * Create a <code>GlassfishDB.MessageMandantID</code> table reference
     */
    public Messagemandantid() {
        this(DSL.name("MessageMandantID"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public Messagemandantid as(String alias) {
        return new Messagemandantid(DSL.name(alias), this);
    }

    @Override
    public Messagemandantid as(Name alias) {
        return new Messagemandantid(alias, this);
    }

    @Override
    public Messagemandantid as(Table<?> alias) {
        return new Messagemandantid(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagemandantid rename(String name) {
        return new Messagemandantid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagemandantid rename(Name name) {
        return new Messagemandantid(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Messagemandantid rename(Table<?> name) {
        return new Messagemandantid(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagemandantid where(Condition condition) {
        return new Messagemandantid(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagemandantid where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagemandantid where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagemandantid where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagemandantid where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagemandantid where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagemandantid where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Messagemandantid where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagemandantid whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Messagemandantid whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
