/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ProcessRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Process extends TableImpl<ProcessRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.Process</code>
     */
    public static final Process PROCESS = new Process();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessRecord> getRecordType() {
        return ProcessRecord.class;
    }

    /**
     * The column <code>GlassfishDB.Process.ProcessID</code>.
     */
    public final TableField<ProcessRecord, String> PROCESSID = createField(DSL.name("ProcessID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.Process.ProcessName</code>.
     */
    public final TableField<ProcessRecord, String> PROCESSNAME = createField(DSL.name("ProcessName"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Process.ProcessDescription</code>.
     */
    public final TableField<ProcessRecord, String> PROCESSDESCRIPTION = createField(DSL.name("ProcessDescription"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.Process.ProjectID</code>.
     */
    public final TableField<ProcessRecord, String> PROJECTID = createField(DSL.name("ProjectID"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Process(Name alias, Table<ProcessRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Process(Name alias, Table<ProcessRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.Process</code> table reference
     */
    public Process(String alias) {
        this(DSL.name(alias), PROCESS);
    }

    /**
     * Create an aliased <code>GlassfishDB.Process</code> table reference
     */
    public Process(Name alias) {
        this(alias, PROCESS);
    }

    /**
     * Create a <code>GlassfishDB.Process</code> table reference
     */
    public Process() {
        this(DSL.name("Process"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROCESS_PRIMARY, Indexes.PROCESS_PROCESS_PROJECTFK);
    }

    @Override
    public UniqueKey<ProcessRecord> getPrimaryKey() {
        return Keys.KEY_PROCESS_PRIMARY;
    }

    @Override
    public Process as(String alias) {
        return new Process(DSL.name(alias), this);
    }

    @Override
    public Process as(Name alias) {
        return new Process(alias, this);
    }

    @Override
    public Process as(Table<?> alias) {
        return new Process(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Process rename(String name) {
        return new Process(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Process rename(Name name) {
        return new Process(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Process rename(Table<?> name) {
        return new Process(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Process where(Condition condition) {
        return new Process(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Process where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Process where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Process where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Process where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Process where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Process where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Process where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Process whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Process whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
