/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ProjectmandantRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Projectmandant extends TableImpl<ProjectmandantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.ProjectMandant</code>
     */
    public static final Projectmandant PROJECTMANDANT = new Projectmandant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectmandantRecord> getRecordType() {
        return ProjectmandantRecord.class;
    }

    /**
     * The column <code>GlassfishDB.ProjectMandant.ProjectID</code>.
     */
    public final TableField<ProjectmandantRecord, String> PROJECTID = createField(DSL.name("ProjectID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.ProjectMandant.MandantID</code>.
     */
    public final TableField<ProjectmandantRecord, String> MANDANTID = createField(DSL.name("MandantID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private Projectmandant(Name alias, Table<ProjectmandantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Projectmandant(Name alias, Table<ProjectmandantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.ProjectMandant</code> table reference
     */
    public Projectmandant(String alias) {
        this(DSL.name(alias), PROJECTMANDANT);
    }

    /**
     * Create an aliased <code>GlassfishDB.ProjectMandant</code> table reference
     */
    public Projectmandant(Name alias) {
        this(alias, PROJECTMANDANT);
    }

    /**
     * Create a <code>GlassfishDB.ProjectMandant</code> table reference
     */
    public Projectmandant() {
        this(DSL.name("ProjectMandant"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROJECTMANDANT_PRIMARY, Indexes.PROJECTMANDANT_PROJECTMANDANT_MANDANT_IDX);
    }

    @Override
    public UniqueKey<ProjectmandantRecord> getPrimaryKey() {
        return Keys.KEY_PROJECTMANDANT_PRIMARY;
    }

    @Override
    public Projectmandant as(String alias) {
        return new Projectmandant(DSL.name(alias), this);
    }

    @Override
    public Projectmandant as(Name alias) {
        return new Projectmandant(alias, this);
    }

    @Override
    public Projectmandant as(Table<?> alias) {
        return new Projectmandant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Projectmandant rename(String name) {
        return new Projectmandant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Projectmandant rename(Name name) {
        return new Projectmandant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Projectmandant rename(Table<?> name) {
        return new Projectmandant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projectmandant where(Condition condition) {
        return new Projectmandant(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projectmandant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projectmandant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projectmandant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projectmandant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projectmandant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projectmandant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projectmandant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projectmandant whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projectmandant whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
