/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ScheduleRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Schedule extends TableImpl<ScheduleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.Schedule</code>
     */
    public static final Schedule SCHEDULE = new Schedule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScheduleRecord> getRecordType() {
        return ScheduleRecord.class;
    }

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleID</code>.
     */
    public final TableField<ScheduleRecord, Short> SCHEDULEID = createField(DSL.name("ScheduleID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleName</code>.
     */
    public final TableField<ScheduleRecord, String> SCHEDULENAME = createField(DSL.name("ScheduleName"), SQLDataType.VARCHAR(150).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleWeekDays</code>.
     */
    public final TableField<ScheduleRecord, String> SCHEDULEWEEKDAYS = createField(DSL.name("ScheduleWeekDays"), SQLDataType.VARCHAR(7).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleDays</code>.
     */
    public final TableField<ScheduleRecord, String> SCHEDULEDAYS = createField(DSL.name("ScheduleDays"), SQLDataType.VARCHAR(31).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleMonths</code>.
     */
    public final TableField<ScheduleRecord, String> SCHEDULEMONTHS = createField(DSL.name("ScheduleMonths"), SQLDataType.VARCHAR(12).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleTimeFrom</code>.
     */
    public final TableField<ScheduleRecord, String> SCHEDULETIMEFROM = createField(DSL.name("ScheduleTimeFrom"), SQLDataType.VARCHAR(5).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleTimeTo</code>.
     */
    public final TableField<ScheduleRecord, String> SCHEDULETIMETO = createField(DSL.name("ScheduleTimeTo"), SQLDataType.VARCHAR(5).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Schedule.ScheduleTimeRepeat</code>.
     */
    public final TableField<ScheduleRecord, Short> SCHEDULETIMEREPEAT = createField(DSL.name("ScheduleTimeRepeat"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.SMALLINT)), this, "");

    private Schedule(Name alias, Table<ScheduleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Schedule(Name alias, Table<ScheduleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.Schedule</code> table reference
     */
    public Schedule(String alias) {
        this(DSL.name(alias), SCHEDULE);
    }

    /**
     * Create an aliased <code>GlassfishDB.Schedule</code> table reference
     */
    public Schedule(Name alias) {
        this(alias, SCHEDULE);
    }

    /**
     * Create a <code>GlassfishDB.Schedule</code> table reference
     */
    public Schedule() {
        this(DSL.name("Schedule"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCHEDULE_PRIMARY);
    }

    @Override
    public UniqueKey<ScheduleRecord> getPrimaryKey() {
        return Keys.KEY_SCHEDULE_PRIMARY;
    }

    @Override
    public Schedule as(String alias) {
        return new Schedule(DSL.name(alias), this);
    }

    @Override
    public Schedule as(Name alias) {
        return new Schedule(alias, this);
    }

    @Override
    public Schedule as(Table<?> alias) {
        return new Schedule(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Schedule rename(String name) {
        return new Schedule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schedule rename(Name name) {
        return new Schedule(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schedule rename(Table<?> name) {
        return new Schedule(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Condition condition) {
        return new Schedule(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schedule where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schedule whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
