/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ScheduletasksRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Scheduletasks extends TableImpl<ScheduletasksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.ScheduleTasks</code>
     */
    public static final Scheduletasks SCHEDULETASKS = new Scheduletasks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScheduletasksRecord> getRecordType() {
        return ScheduletasksRecord.class;
    }

    /**
     * The column <code>GlassfishDB.ScheduleTasks.ActionID</code>.
     */
    public final TableField<ScheduletasksRecord, String> ACTIONID = createField(DSL.name("ActionID"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.ScheduleTasks.Execution</code>.
     */
    public final TableField<ScheduletasksRecord, LocalDateTime> EXECUTION = createField(DSL.name("Execution"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private Scheduletasks(Name alias, Table<ScheduletasksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Scheduletasks(Name alias, Table<ScheduletasksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.ScheduleTasks</code> table reference
     */
    public Scheduletasks(String alias) {
        this(DSL.name(alias), SCHEDULETASKS);
    }

    /**
     * Create an aliased <code>GlassfishDB.ScheduleTasks</code> table reference
     */
    public Scheduletasks(Name alias) {
        this(alias, SCHEDULETASKS);
    }

    /**
     * Create a <code>GlassfishDB.ScheduleTasks</code> table reference
     */
    public Scheduletasks() {
        this(DSL.name("ScheduleTasks"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCHEDULETASKS_PRIMARY);
    }

    @Override
    public UniqueKey<ScheduletasksRecord> getPrimaryKey() {
        return Keys.KEY_SCHEDULETASKS_PRIMARY;
    }

    @Override
    public Scheduletasks as(String alias) {
        return new Scheduletasks(DSL.name(alias), this);
    }

    @Override
    public Scheduletasks as(Name alias) {
        return new Scheduletasks(alias, this);
    }

    @Override
    public Scheduletasks as(Table<?> alias) {
        return new Scheduletasks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Scheduletasks rename(String name) {
        return new Scheduletasks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Scheduletasks rename(Name name) {
        return new Scheduletasks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Scheduletasks rename(Table<?> name) {
        return new Scheduletasks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Scheduletasks where(Condition condition) {
        return new Scheduletasks(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Scheduletasks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Scheduletasks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Scheduletasks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Scheduletasks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Scheduletasks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Scheduletasks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Scheduletasks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Scheduletasks whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Scheduletasks whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
