/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServicetypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servicetype extends TableImpl<ServicetypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.ServiceType</code>
     */
    public static final Servicetype SERVICETYPE = new Servicetype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServicetypeRecord> getRecordType() {
        return ServicetypeRecord.class;
    }

    /**
     * The column <code>GlassfishDB.ServiceType.ServiceTypeID</code>.
     */
    public final TableField<ServicetypeRecord, Short> SERVICETYPEID = createField(DSL.name("ServiceTypeID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.ServiceType.ServiceTypeName</code>.
     */
    public final TableField<ServicetypeRecord, String> SERVICETYPENAME = createField(DSL.name("ServiceTypeName"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.ServiceType.ServiceGroupID</code>.
     */
    public final TableField<ServicetypeRecord, Short> SERVICEGROUPID = createField(DSL.name("ServiceGroupID"), SQLDataType.SMALLINT.nullable(false), this, "");

    private Servicetype(Name alias, Table<ServicetypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Servicetype(Name alias, Table<ServicetypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.ServiceType</code> table reference
     */
    public Servicetype(String alias) {
        this(DSL.name(alias), SERVICETYPE);
    }

    /**
     * Create an aliased <code>GlassfishDB.ServiceType</code> table reference
     */
    public Servicetype(Name alias) {
        this(alias, SERVICETYPE);
    }

    /**
     * Create a <code>GlassfishDB.ServiceType</code> table reference
     */
    public Servicetype() {
        this(DSL.name("ServiceType"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICETYPE_PRIMARY, Indexes.SERVICETYPE_SERVICETYPE_SERVICEGROUPFK);
    }

    @Override
    public UniqueKey<ServicetypeRecord> getPrimaryKey() {
        return Keys.KEY_SERVICETYPE_PRIMARY;
    }

    @Override
    public Servicetype as(String alias) {
        return new Servicetype(DSL.name(alias), this);
    }

    @Override
    public Servicetype as(Name alias) {
        return new Servicetype(alias, this);
    }

    @Override
    public Servicetype as(Table<?> alias) {
        return new Servicetype(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetype rename(String name) {
        return new Servicetype(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetype rename(Name name) {
        return new Servicetype(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetype rename(Table<?> name) {
        return new Servicetype(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetype where(Condition condition) {
        return new Servicetype(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetype where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetype where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetype where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetype where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetype where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetype where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetype where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetype whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetype whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
