/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServicetaskRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servicetask extends TableImpl<ServicetaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.ServiceTask</code>
     */
    public static final Servicetask SERVICETASK = new Servicetask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServicetaskRecord> getRecordType() {
        return ServicetaskRecord.class;
    }

    /**
     * The column <code>GlassfishDB.ServiceTask.ServiceID</code>.
     */
    public final TableField<ServicetaskRecord, String> SERVICEID = createField(DSL.name("ServiceID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.ServiceTask.ServiceTaskID</code>.
     */
    public final TableField<ServicetaskRecord, Short> SERVICETASKID = createField(DSL.name("ServiceTaskID"), SQLDataType.SMALLINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>GlassfishDB.ServiceTask.ServiceTaskName</code>.
     */
    public final TableField<ServicetaskRecord, String> SERVICETASKNAME = createField(DSL.name("ServiceTaskName"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.ServiceTask.ServiceTaskProperties</code>.
     */
    public final TableField<ServicetaskRecord, String> SERVICETASKPROPERTIES = createField(DSL.name("ServiceTaskProperties"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    private Servicetask(Name alias, Table<ServicetaskRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Servicetask(Name alias, Table<ServicetaskRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.ServiceTask</code> table reference
     */
    public Servicetask(String alias) {
        this(DSL.name(alias), SERVICETASK);
    }

    /**
     * Create an aliased <code>GlassfishDB.ServiceTask</code> table reference
     */
    public Servicetask(Name alias) {
        this(alias, SERVICETASK);
    }

    /**
     * Create a <code>GlassfishDB.ServiceTask</code> table reference
     */
    public Servicetask() {
        this(DSL.name("ServiceTask"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICETASK_PRIMARY, Indexes.SERVICETASK_SERVICETASK_SERVICEFK);
    }

    @Override
    public Identity<ServicetaskRecord, Short> getIdentity() {
        return (Identity<ServicetaskRecord, Short>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServicetaskRecord> getPrimaryKey() {
        return Keys.KEY_SERVICETASK_PRIMARY;
    }

    @Override
    public Servicetask as(String alias) {
        return new Servicetask(DSL.name(alias), this);
    }

    @Override
    public Servicetask as(Name alias) {
        return new Servicetask(alias, this);
    }

    @Override
    public Servicetask as(Table<?> alias) {
        return new Servicetask(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetask rename(String name) {
        return new Servicetask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetask rename(Name name) {
        return new Servicetask(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetask rename(Table<?> name) {
        return new Servicetask(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetask where(Condition condition) {
        return new Servicetask(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetask where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetask where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetask where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetask where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetask where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetask where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetask where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetask whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetask whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
