/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServicegroupRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servicegroup extends TableImpl<ServicegroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.ServiceGroup</code>
     */
    public static final Servicegroup SERVICEGROUP = new Servicegroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServicegroupRecord> getRecordType() {
        return ServicegroupRecord.class;
    }

    /**
     * The column <code>GlassfishDB.ServiceGroup.ServiceGroupID</code>.
     */
    public final TableField<ServicegroupRecord, Short> SERVICEGROUPID = createField(DSL.name("ServiceGroupID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.ServiceGroup.ServiceGroupName</code>.
     */
    public final TableField<ServicegroupRecord, String> SERVICEGROUPNAME = createField(DSL.name("ServiceGroupName"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Servicegroup(Name alias, Table<ServicegroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Servicegroup(Name alias, Table<ServicegroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.ServiceGroup</code> table reference
     */
    public Servicegroup(String alias) {
        this(DSL.name(alias), SERVICEGROUP);
    }

    /**
     * Create an aliased <code>GlassfishDB.ServiceGroup</code> table reference
     */
    public Servicegroup(Name alias) {
        this(alias, SERVICEGROUP);
    }

    /**
     * Create a <code>GlassfishDB.ServiceGroup</code> table reference
     */
    public Servicegroup() {
        this(DSL.name("ServiceGroup"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICEGROUP_PRIMARY);
    }

    @Override
    public UniqueKey<ServicegroupRecord> getPrimaryKey() {
        return Keys.KEY_SERVICEGROUP_PRIMARY;
    }

    @Override
    public Servicegroup as(String alias) {
        return new Servicegroup(DSL.name(alias), this);
    }

    @Override
    public Servicegroup as(Name alias) {
        return new Servicegroup(alias, this);
    }

    @Override
    public Servicegroup as(Table<?> alias) {
        return new Servicegroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicegroup rename(String name) {
        return new Servicegroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicegroup rename(Name name) {
        return new Servicegroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicegroup rename(Table<?> name) {
        return new Servicegroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicegroup where(Condition condition) {
        return new Servicegroup(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicegroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicegroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicegroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicegroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicegroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicegroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicegroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicegroup whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicegroup whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
