/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServiceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Service extends TableImpl<ServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.Service</code>
     */
    public static final Service SERVICE = new Service();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceRecord> getRecordType() {
        return ServiceRecord.class;
    }

    /**
     * The column <code>GlassfishDB.Service.ServiceID</code>.
     */
    public final TableField<ServiceRecord, String> SERVICEID = createField(DSL.name("ServiceID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceTypeID</code>.
     */
    public final TableField<ServiceRecord, Short> SERVICETYPEID = createField(DSL.name("ServiceTypeID"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceConnectString</code>.
     */
    public final TableField<ServiceRecord, String> SERVICECONNECTSTRING = createField(DSL.name("ServiceConnectString"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceName</code>.
     */
    public final TableField<ServiceRecord, String> SERVICENAME = createField(DSL.name("ServiceName"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceDescription</code>.
     */
    public final TableField<ServiceRecord, String> SERVICEDESCRIPTION = createField(DSL.name("ServiceDescription"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceStatus</code>.
     */
    public final TableField<ServiceRecord, String> SERVICESTATUS = createField(DSL.name("ServiceStatus"), SQLDataType.VARCHAR(30).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceLastUpdate</code>.
     */
    public final TableField<ServiceRecord, LocalDateTime> SERVICELASTUPDATE = createField(DSL.name("ServiceLastUpdate"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceLastStatusMessage</code>.
     */
    public final TableField<ServiceRecord, String> SERVICELASTSTATUSMESSAGE = createField(DSL.name("ServiceLastStatusMessage"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceTimeout</code>.
     */
    public final TableField<ServiceRecord, Short> SERVICETIMEOUT = createField(DSL.name("ServiceTimeout"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>GlassfishDB.Service.ServiceDefaultFileStore</code>.
     */
    public final TableField<ServiceRecord, String> SERVICEDEFAULTFILESTORE = createField(DSL.name("ServiceDefaultFileStore"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Service(Name alias, Table<ServiceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Service(Name alias, Table<ServiceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.Service</code> table reference
     */
    public Service(String alias) {
        this(DSL.name(alias), SERVICE);
    }

    /**
     * Create an aliased <code>GlassfishDB.Service</code> table reference
     */
    public Service(Name alias) {
        this(alias, SERVICE);
    }

    /**
     * Create a <code>GlassfishDB.Service</code> table reference
     */
    public Service() {
        this(DSL.name("Service"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICE_PRIMARY, Indexes.SERVICE_SERVICE_SERVICETYPEFK);
    }

    @Override
    public UniqueKey<ServiceRecord> getPrimaryKey() {
        return Keys.KEY_SERVICE_PRIMARY;
    }

    @Override
    public Service as(String alias) {
        return new Service(DSL.name(alias), this);
    }

    @Override
    public Service as(Name alias) {
        return new Service(alias, this);
    }

    @Override
    public Service as(Table<?> alias) {
        return new Service(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(String name) {
        return new Service(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(Name name) {
        return new Service(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(Table<?> name) {
        return new Service(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Condition condition) {
        return new Service(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
