/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.SosRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Sequence of Services
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sos extends TableImpl<SosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.SOS</code>
     */
    public static final Sos SOS = new Sos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SosRecord> getRecordType() {
        return SosRecord.class;
    }

    /**
     * The column <code>GlassfishDB.SOS.SOSID</code>.
     */
    public final TableField<SosRecord, String> SOSID = createField(DSL.name("SOSID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.SOS.SOSName</code>.
     */
    public final TableField<SosRecord, String> SOSNAME = createField(DSL.name("SOSName"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.SOS.SOSDescription</code>.
     */
    public final TableField<SosRecord, String> SOSDESCRIPTION = createField(DSL.name("SOSDescription"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.SOS.ProcessID</code>.
     */
    public final TableField<SosRecord, String> PROCESSID = createField(DSL.name("ProcessID"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Sos(Name alias, Table<SosRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sos(Name alias, Table<SosRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Sequence of Services"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.SOS</code> table reference
     */
    public Sos(String alias) {
        this(DSL.name(alias), SOS);
    }

    /**
     * Create an aliased <code>GlassfishDB.SOS</code> table reference
     */
    public Sos(Name alias) {
        this(alias, SOS);
    }

    /**
     * Create a <code>GlassfishDB.SOS</code> table reference
     */
    public Sos() {
        this(DSL.name("SOS"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SOS_PRIMARY, Indexes.SOS_SOS_PROCESSFK);
    }

    @Override
    public UniqueKey<SosRecord> getPrimaryKey() {
        return Keys.KEY_SOS_PRIMARY;
    }

    @Override
    public Sos as(String alias) {
        return new Sos(DSL.name(alias), this);
    }

    @Override
    public Sos as(Name alias) {
        return new Sos(alias, this);
    }

    @Override
    public Sos as(Table<?> alias) {
        return new Sos(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sos rename(String name) {
        return new Sos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sos rename(Name name) {
        return new Sos(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sos rename(Table<?> name) {
        return new Sos(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sos where(Condition condition) {
        return new Sos(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sos where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sos where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sos where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sos where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sos where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sos where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sos where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sos whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sos whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
