/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.SosactionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sosaction extends TableImpl<SosactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB.SOSAction</code>
     */
    public static final Sosaction SOSACTION = new Sosaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SosactionRecord> getRecordType() {
        return SosactionRecord.class;
    }

    /**
     * The column <code>GlassfishDB.SOSAction.SOSID</code>.
     */
    public final TableField<SosactionRecord, String> SOSID = createField(DSL.name("SOSID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.SOSAction.SOSActionID</code>.
     */
    public final TableField<SosactionRecord, Short> SOSACTIONID = createField(DSL.name("SOSActionID"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>GlassfishDB.SOSAction.SOSActionName</code>.
     */
    public final TableField<SosactionRecord, String> SOSACTIONNAME = createField(DSL.name("SOSActionName"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.SOSAction.ServiceID</code>.
     */
    public final TableField<SosactionRecord, String> SERVICEID = createField(DSL.name("ServiceID"), SQLDataType.VARCHAR(36).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>GlassfishDB.SOSAction.SOSActionServiceProperties</code>.
     */
    public final TableField<SosactionRecord, String> SOSACTIONSERVICEPROPERTIES = createField(DSL.name("SOSActionServiceProperties"), SQLDataType.CLOB(16777215).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>GlassfishDB.SOSAction.SOSActionTimeout</code>.
     */
    public final TableField<SosactionRecord, Short> SOSACTIONTIMEOUT = createField(DSL.name("SOSActionTimeout"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.SMALLINT)), this, "");

    private Sosaction(Name alias, Table<SosactionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sosaction(Name alias, Table<SosactionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.SOSAction</code> table reference
     */
    public Sosaction(String alias) {
        this(DSL.name(alias), SOSACTION);
    }

    /**
     * Create an aliased <code>GlassfishDB.SOSAction</code> table reference
     */
    public Sosaction(Name alias) {
        this(alias, SOSACTION);
    }

    /**
     * Create a <code>GlassfishDB.SOSAction</code> table reference
     */
    public Sosaction() {
        this(DSL.name("SOSAction"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SOSACTION_PRIMARY, Indexes.SOSACTION_SOSACTION_SERVICEFK, Indexes.SOSACTION_SOSACTION_SOSFK);
    }

    @Override
    public UniqueKey<SosactionRecord> getPrimaryKey() {
        return Keys.KEY_SOSACTION_PRIMARY;
    }

    @Override
    public Sosaction as(String alias) {
        return new Sosaction(DSL.name(alias), this);
    }

    @Override
    public Sosaction as(Name alias) {
        return new Sosaction(alias, this);
    }

    @Override
    public Sosaction as(Table<?> alias) {
        return new Sosaction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sosaction rename(String name) {
        return new Sosaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sosaction rename(Name name) {
        return new Sosaction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sosaction rename(Table<?> name) {
        return new Sosaction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosaction where(Condition condition) {
        return new Sosaction(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosaction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosaction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosaction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosaction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosaction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosaction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosaction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosaction whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosaction whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
