/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish.tables;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.Glassfishdb;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Indexes;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.Keys;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.SosdefaultmessagepropertyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sosdefaultmessageproperty extends TableImpl<SosdefaultmessagepropertyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>GlassfishDB.SOSDefaultMessageProperty</code>
     */
    public static final Sosdefaultmessageproperty SOSDEFAULTMESSAGEPROPERTY = new Sosdefaultmessageproperty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SosdefaultmessagepropertyRecord> getRecordType() {
        return SosdefaultmessagepropertyRecord.class;
    }

    /**
     * The column <code>GlassfishDB.SOSDefaultMessageProperty.SOSID</code>.
     */
    public final TableField<SosdefaultmessagepropertyRecord, String> SOSID = createField(DSL.name("SOSID"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column
     * <code>GlassfishDB.SOSDefaultMessageProperty.MessagePropertyName</code>.
     */
    public final TableField<SosdefaultmessagepropertyRecord, String> MESSAGEPROPERTYNAME = createField(DSL.name("MessagePropertyName"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column
     * <code>GlassfishDB.SOSDefaultMessageProperty.MessagePropertyValue</code>.
     */
    public final TableField<SosdefaultmessagepropertyRecord, String> MESSAGEPROPERTYVALUE = createField(DSL.name("MessagePropertyValue"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Sosdefaultmessageproperty(Name alias, Table<SosdefaultmessagepropertyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sosdefaultmessageproperty(Name alias, Table<SosdefaultmessagepropertyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GlassfishDB.SOSDefaultMessageProperty</code>
     * table reference
     */
    public Sosdefaultmessageproperty(String alias) {
        this(DSL.name(alias), SOSDEFAULTMESSAGEPROPERTY);
    }

    /**
     * Create an aliased <code>GlassfishDB.SOSDefaultMessageProperty</code>
     * table reference
     */
    public Sosdefaultmessageproperty(Name alias) {
        this(alias, SOSDEFAULTMESSAGEPROPERTY);
    }

    /**
     * Create a <code>GlassfishDB.SOSDefaultMessageProperty</code> table
     * reference
     */
    public Sosdefaultmessageproperty() {
        this(DSL.name("SOSDefaultMessageProperty"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Glassfishdb.GLASSFISHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SOSDEFAULTMESSAGEPROPERTY_PRIMARY, Indexes.SOSDEFAULTMESSAGEPROPERTY_SOSDEFAULTMESSAGEPROPERTY_SOSFK);
    }

    @Override
    public UniqueKey<SosdefaultmessagepropertyRecord> getPrimaryKey() {
        return Keys.KEY_SOSDEFAULTMESSAGEPROPERTY_PRIMARY;
    }

    @Override
    public Sosdefaultmessageproperty as(String alias) {
        return new Sosdefaultmessageproperty(DSL.name(alias), this);
    }

    @Override
    public Sosdefaultmessageproperty as(Name alias) {
        return new Sosdefaultmessageproperty(alias, this);
    }

    @Override
    public Sosdefaultmessageproperty as(Table<?> alias) {
        return new Sosdefaultmessageproperty(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sosdefaultmessageproperty rename(String name) {
        return new Sosdefaultmessageproperty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sosdefaultmessageproperty rename(Name name) {
        return new Sosdefaultmessageproperty(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sosdefaultmessageproperty rename(Table<?> name) {
        return new Sosdefaultmessageproperty(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosdefaultmessageproperty where(Condition condition) {
        return new Sosdefaultmessageproperty(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosdefaultmessageproperty where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosdefaultmessageproperty where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosdefaultmessageproperty where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosdefaultmessageproperty where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosdefaultmessageproperty where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosdefaultmessageproperty where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sosdefaultmessageproperty where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosdefaultmessageproperty whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sosdefaultmessageproperty whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
