/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Mandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Message;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebam;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebammandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebamtype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagemandantid;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagepropertysearchlistentry;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistic;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistichistory;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Process;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Project;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Projectmandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Schedule;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduleplans;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduletasks;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Service;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicegroup;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetask;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sos;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosdefaultmessageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Glassfishdb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GlassfishDB</code>
     */
    public static final Glassfishdb GLASSFISHDB = new Glassfishdb();

    /**
     * The table <code>GlassfishDB.Mandant</code>.
     */
    public final Mandant MANDANT = Mandant.MANDANT;

    /**
     * The table <code>GlassfishDB.Message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>GlassfishDB.MessageAction</code>.
     */
    public final Messageaction MESSAGEACTION = Messageaction.MESSAGEACTION;

    /**
     * The table <code>GlassfishDB.MessageBAM</code>.
     */
    public final Messagebam MESSAGEBAM = Messagebam.MESSAGEBAM;

    /**
     * The table <code>GlassfishDB.MessageBAMMandant</code>.
     */
    public final Messagebammandant MESSAGEBAMMANDANT = Messagebammandant.MESSAGEBAMMANDANT;

    /**
     * The table <code>GlassfishDB.MessageBAMType</code>.
     */
    public final Messagebamtype MESSAGEBAMTYPE = Messagebamtype.MESSAGEBAMTYPE;

    /**
     * The table <code>GlassfishDB.MessageMandantID</code>.
     */
    public final Messagemandantid MESSAGEMANDANTID = Messagemandantid.MESSAGEMANDANTID;

    /**
     * The table <code>GlassfishDB.MessageProperty</code>.
     */
    public final Messageproperty MESSAGEPROPERTY = Messageproperty.MESSAGEPROPERTY;

    /**
     * The table <code>GlassfishDB.MessagePropertySearchListEntry</code>.
     */
    public final Messagepropertysearchlistentry MESSAGEPROPERTYSEARCHLISTENTRY = Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY;

    /**
     * The table <code>GlassfishDB.MessageStatistic</code>.
     */
    public final Messagestatistic MESSAGESTATISTIC = Messagestatistic.MESSAGESTATISTIC;

    /**
     * The table <code>GlassfishDB.MessageStatisticHistory</code>.
     */
    public final Messagestatistichistory MESSAGESTATISTICHISTORY = Messagestatistichistory.MESSAGESTATISTICHISTORY;

    /**
     * The table <code>GlassfishDB.Process</code>.
     */
    public final Process PROCESS = Process.PROCESS;

    /**
     * The table <code>GlassfishDB.Project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>GlassfishDB.ProjectMandant</code>.
     */
    public final Projectmandant PROJECTMANDANT = Projectmandant.PROJECTMANDANT;

    /**
     * The table <code>GlassfishDB.Schedule</code>.
     */
    public final Schedule SCHEDULE = Schedule.SCHEDULE;

    /**
     * The table <code>GlassfishDB.SchedulePlans</code>.
     */
    public final Scheduleplans SCHEDULEPLANS = Scheduleplans.SCHEDULEPLANS;

    /**
     * The table <code>GlassfishDB.ScheduleTasks</code>.
     */
    public final Scheduletasks SCHEDULETASKS = Scheduletasks.SCHEDULETASKS;

    /**
     * The table <code>GlassfishDB.Service</code>.
     */
    public final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>GlassfishDB.ServiceGroup</code>.
     */
    public final Servicegroup SERVICEGROUP = Servicegroup.SERVICEGROUP;

    /**
     * The table <code>GlassfishDB.ServiceTask</code>.
     */
    public final Servicetask SERVICETASK = Servicetask.SERVICETASK;

    /**
     * The table <code>GlassfishDB.ServiceType</code>.
     */
    public final Servicetype SERVICETYPE = Servicetype.SERVICETYPE;

    /**
     * Sequence of Services
     */
    public final Sos SOS = Sos.SOS;

    /**
     * The table <code>GlassfishDB.SOSAction</code>.
     */
    public final Sosaction SOSACTION = Sosaction.SOSACTION;

    /**
     * The table <code>GlassfishDB.SOSDefaultMessageProperty</code>.
     */
    public final Sosdefaultmessageproperty SOSDEFAULTMESSAGEPROPERTY = Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY;

    /**
     * The table <code>GlassfishDB.User</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Glassfishdb() {
        super(DSL.name("GlassfishDB"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Mandant.MANDANT,
            Message.MESSAGE,
            Messageaction.MESSAGEACTION,
            Messagebam.MESSAGEBAM,
            Messagebammandant.MESSAGEBAMMANDANT,
            Messagebamtype.MESSAGEBAMTYPE,
            Messagemandantid.MESSAGEMANDANTID,
            Messageproperty.MESSAGEPROPERTY,
            Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY,
            Messagestatistic.MESSAGESTATISTIC,
            Messagestatistichistory.MESSAGESTATISTICHISTORY,
            Process.PROCESS,
            Project.PROJECT,
            Projectmandant.PROJECTMANDANT,
            Schedule.SCHEDULE,
            Scheduleplans.SCHEDULEPLANS,
            Scheduletasks.SCHEDULETASKS,
            Service.SERVICE,
            Servicegroup.SERVICEGROUP,
            Servicetask.SERVICETASK,
            Servicetype.SERVICETYPE,
            Sos.SOS,
            Sosaction.SOSACTION,
            Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY,
            User.USER
        );
    }
}
