/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Mandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Message;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebam;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebammandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebamtype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagepropertysearchlistentry;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistichistory;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Process;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Project;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Projectmandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Schedule;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduleplans;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduletasks;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Service;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicegroup;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetask;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sos;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosdefaultmessageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in GlassfishDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MESSAGEBAMMANDANT_MANDANTIDSORTINDEXBAMTYPEIDX = Internal.createIndex(DSL.name("MandantIDSortIndexBAMTYpeIDX"), Messagebammandant.MESSAGEBAMMANDANT, new OrderField[] { Messagebammandant.MESSAGEBAMMANDANT.MANDANTID, Messagebammandant.MESSAGEBAMMANDANT.MESSAGEBAMTYPESORTINDEX, Messagebammandant.MESSAGEBAMMANDANT.MESSAGEBAMTYPE }, false);
    public static final Index MESSAGE_MESSAGE_PROCESSFK = Internal.createIndex(DSL.name("Message_ProcessFK"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.PROCESSID }, false);
    public static final Index MESSAGEACTION_MESSAGEACTION_MESSAGEFK = Internal.createIndex(DSL.name("MessageAction_MessageFK"), Messageaction.MESSAGEACTION, new OrderField[] { Messageaction.MESSAGEACTION.MESSAGEID }, false);
    public static final Index MESSAGEBAM_MESSAGEBAM_BAMVALUE = Internal.createIndex(DSL.name("MessageBAM_BAMValue"), Messagebam.MESSAGEBAM, new OrderField[] { Messagebam.MESSAGEBAM.MESSAGEBAMTYPE, Messagebam.MESSAGEBAM.MESSAGEBAMVALUE }, false);
    public static final Index MESSAGEBAM_MESSAGEBAM_BAMVALUEONLY = Internal.createIndex(DSL.name("MessageBAM_BAMValueOnly"), Messagebam.MESSAGEBAM, new OrderField[] { Messagebam.MESSAGEBAM.MESSAGEBAMVALUE }, false);
    public static final Index MESSAGEBAM_MESSAGEBAM_MESSAGEFK = Internal.createIndex(DSL.name("MessageBAM_MessageFK"), Messagebam.MESSAGEBAM, new OrderField[] { Messagebam.MESSAGEBAM.MESSAGEID }, false);
    public static final Index MESSAGEBAM_MESSAGEBAM_MESSAGEID = Internal.createIndex(DSL.name("MessageBAM_MessageID"), Messagebam.MESSAGEBAM, new OrderField[] { Messagebam.MESSAGEBAM.MESSAGEID, Messagebam.MESSAGEBAM.MESSAGEBAMTYPE }, false);
    public static final Index MESSAGE_MESSAGELASTUPDATEIDX = Internal.createIndex(DSL.name("MessageLastUpdateIDX"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.MESSAGELASTUPDATE }, false);
    public static final Index MESSAGE_MESSAGELASTUPDATEPROCESSMESSAGEIDX = Internal.createIndex(DSL.name("MessageLastUpdateProcessMessageIDX"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.MESSAGELASTUPDATE, Message.MESSAGE.PROCESSID, Message.MESSAGE.MESSAGEID }, false);
    public static final Index MESSAGEPROPERTY_MESSAGEPROPERTY_MESSAGEACTIONFK = Internal.createIndex(DSL.name("MessageProperty_MessageActionFK"), Messageproperty.MESSAGEPROPERTY, new OrderField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEID, Messageproperty.MESSAGEPROPERTY.MESSAGEACTIONID }, false);
    public static final Index MESSAGEPROPERTY_MESSAGEPROPERTY_MESSAGEFK = Internal.createIndex(DSL.name("MessageProperty_MessageFK"), Messageproperty.MESSAGEPROPERTY, new OrderField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEID }, false);
    public static final Index MESSAGEPROPERTY_MESSAGEPROPERTYNAMEIDX = Internal.createIndex(DSL.name("MessagePropertyNameIDX"), Messageproperty.MESSAGEPROPERTY, new OrderField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEPROPERTYNAME }, false);
    public static final Index MESSAGEPROPERTY_MESSAGEPROPERTYNAMEVALUEIDX = Internal.createIndex(DSL.name("MessagePropertyNameValueIDX"), Messageproperty.MESSAGEPROPERTY, new OrderField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEPROPERTYNAME, Messageproperty.MESSAGEPROPERTY.MESSAGEPROPERTYVALUE }, false);
    public static final Index MESSAGEPROPERTY_MESSAGEPROPERTYVALUEIDX = Internal.createIndex(DSL.name("MessagePropertyValueIDX"), Messageproperty.MESSAGEPROPERTY, new OrderField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEPROPERTYVALUE }, false);
    public static final Index MESSAGE_MESSAGESTATUSIDX = Internal.createIndex(DSL.name("MessageStatusIDX"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.MESSAGESTATUS }, false);
    public static final Index MANDANT_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Mandant.MANDANT, new OrderField[] { Mandant.MANDANT.MANDANTID }, true);
    public static final Index MESSAGE_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.MESSAGEID }, true);
    public static final Index MESSAGEACTION_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messageaction.MESSAGEACTION, new OrderField[] { Messageaction.MESSAGEACTION.MESSAGEID, Messageaction.MESSAGEACTION.MESSAGEACTIONID }, true);
    public static final Index MESSAGEBAM_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messagebam.MESSAGEBAM, new OrderField[] { Messagebam.MESSAGEBAM.MESSAGEID, Messagebam.MESSAGEBAM.MESSAGEBAMTYPE, Messagebam.MESSAGEBAM.MESSAGEBAMVALUE }, true);
    public static final Index MESSAGEBAMMANDANT_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messagebammandant.MESSAGEBAMMANDANT, new OrderField[] { Messagebammandant.MESSAGEBAMMANDANT.MESSAGEBAMTYPE, Messagebammandant.MESSAGEBAMMANDANT.MANDANTID }, true);
    public static final Index MESSAGEBAMTYPE_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messagebamtype.MESSAGEBAMTYPE, new OrderField[] { Messagebamtype.MESSAGEBAMTYPE.MESSAGEBAMTYPE_ }, true);
    public static final Index MESSAGEPROPERTY_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messageproperty.MESSAGEPROPERTY, new OrderField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEID, Messageproperty.MESSAGEPROPERTY.MESSAGEPROPERTYNAME, Messageproperty.MESSAGEPROPERTY.MESSAGEACTIONID }, true);
    public static final Index MESSAGEPROPERTYSEARCHLISTENTRY_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY, new OrderField[] { Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY.MESSAGEPROPERTYNAME }, true);
    public static final Index MESSAGESTATISTICHISTORY_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Messagestatistichistory.MESSAGESTATISTICHISTORY, new OrderField[] { Messagestatistichistory.MESSAGESTATISTICHISTORY.PERIOD }, true);
    public static final Index PROCESS_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Process.PROCESS, new OrderField[] { Process.PROCESS.PROCESSID }, true);
    public static final Index PROJECT_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Project.PROJECT, new OrderField[] { Project.PROJECT.PROJECTID }, true);
    public static final Index PROJECTMANDANT_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Projectmandant.PROJECTMANDANT, new OrderField[] { Projectmandant.PROJECTMANDANT.PROJECTID, Projectmandant.PROJECTMANDANT.MANDANTID }, true);
    public static final Index SCHEDULE_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Schedule.SCHEDULE, new OrderField[] { Schedule.SCHEDULE.SCHEDULEID }, true);
    public static final Index SCHEDULEPLANS_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Scheduleplans.SCHEDULEPLANS, new OrderField[] { Scheduleplans.SCHEDULEPLANS.SCHEDULEID, Scheduleplans.SCHEDULEPLANS.ACTIONID }, true);
    public static final Index SCHEDULETASKS_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Scheduletasks.SCHEDULETASKS, new OrderField[] { Scheduletasks.SCHEDULETASKS.ACTIONID, Scheduletasks.SCHEDULETASKS.EXECUTION }, true);
    public static final Index SERVICE_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Service.SERVICE, new OrderField[] { Service.SERVICE.SERVICEID }, true);
    public static final Index SERVICEGROUP_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Servicegroup.SERVICEGROUP, new OrderField[] { Servicegroup.SERVICEGROUP.SERVICEGROUPID }, true);
    public static final Index SERVICETASK_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Servicetask.SERVICETASK, new OrderField[] { Servicetask.SERVICETASK.SERVICETASKID, Servicetask.SERVICETASK.SERVICEID }, true);
    public static final Index SERVICETYPE_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Servicetype.SERVICETYPE, new OrderField[] { Servicetype.SERVICETYPE.SERVICETYPEID }, true);
    public static final Index SOS_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Sos.SOS, new OrderField[] { Sos.SOS.SOSID }, true);
    public static final Index SOSACTION_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Sosaction.SOSACTION, new OrderField[] { Sosaction.SOSACTION.SOSID, Sosaction.SOSACTION.SOSACTIONID }, true);
    public static final Index SOSDEFAULTMESSAGEPROPERTY_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY, new OrderField[] { Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY.SOSID, Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY.MESSAGEPROPERTYNAME }, true);
    public static final Index USER_PRIMARY = Internal.createIndex(DSL.name("PRIMARY"), User.USER, new OrderField[] { User.USER.USERID }, true);
    public static final Index PROCESS_PROCESS_PROJECTFK = Internal.createIndex(DSL.name("Process_ProjectFK"), Process.PROCESS, new OrderField[] { Process.PROCESS.PROJECTID }, false);
    public static final Index MESSAGE_PROEJCTIDIDX = Internal.createIndex(DSL.name("ProejctIDIDX"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.PROCESSID }, false);
    public static final Index PROJECTMANDANT_PROJECTMANDANT_MANDANT_IDX = Internal.createIndex(DSL.name("ProjectMandant_Mandant_idx"), Projectmandant.PROJECTMANDANT, new OrderField[] { Projectmandant.PROJECTMANDANT.MANDANTID }, false);
    public static final Index SCHEDULEPLANS_SCHEDULEPLANS_SCHEDULEFK = Internal.createIndex(DSL.name("SchedulePlans_ScheduleFK"), Scheduleplans.SCHEDULEPLANS, new OrderField[] { Scheduleplans.SCHEDULEPLANS.SCHEDULEID }, false);
    public static final Index SERVICE_SERVICE_SERVICETYPEFK = Internal.createIndex(DSL.name("Service_ServiceTypeFK"), Service.SERVICE, new OrderField[] { Service.SERVICE.SERVICETYPEID }, false);
    public static final Index SERVICETASK_SERVICETASK_SERVICEFK = Internal.createIndex(DSL.name("ServiceTask_ServiceFK"), Servicetask.SERVICETASK, new OrderField[] { Servicetask.SERVICETASK.SERVICEID }, false);
    public static final Index SERVICETYPE_SERVICETYPE_SERVICEGROUPFK = Internal.createIndex(DSL.name("ServiceType_ServiceGroupFK"), Servicetype.SERVICETYPE, new OrderField[] { Servicetype.SERVICETYPE.SERVICEGROUPID }, false);
    public static final Index SOS_SOS_PROCESSFK = Internal.createIndex(DSL.name("SOS_ProcessFK"), Sos.SOS, new OrderField[] { Sos.SOS.PROCESSID }, false);
    public static final Index SOSACTION_SOSACTION_SERVICEFK = Internal.createIndex(DSL.name("SOSAction_ServiceFK"), Sosaction.SOSACTION, new OrderField[] { Sosaction.SOSACTION.SERVICEID }, false);
    public static final Index SOSACTION_SOSACTION_SOSFK = Internal.createIndex(DSL.name("SOSAction_SOSFK"), Sosaction.SOSACTION, new OrderField[] { Sosaction.SOSACTION.SOSID }, false);
    public static final Index SOSDEFAULTMESSAGEPROPERTY_SOSDEFAULTMESSAGEPROPERTY_SOSFK = Internal.createIndex(DSL.name("SOSDefaultMessageProperty_SOSFK"), Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY, new OrderField[] { Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY.SOSID }, false);
    public static final Index MESSAGE_SOURCEMESSAGEIDIDX = Internal.createIndex(DSL.name("SourceMessageIDIDX"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.SOURCEMESSAGEID }, false);
    public static final Index MESSAGE_TARGETMESSAGEIDIDX = Internal.createIndex(DSL.name("TargetMessageIDIDX"), Message.MESSAGE, new OrderField[] { Message.MESSAGE.TARGETMESSAGEID }, false);
    public static final Index USER_USER_MANDANTFK = Internal.createIndex(DSL.name("User_MandantFK"), User.USER, new OrderField[] { User.USER.MANDANTID }, false);
}
