/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Mandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Message;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebam;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebammandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebamtype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagepropertysearchlistentry;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistichistory;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Process;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Project;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Projectmandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Schedule;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduleplans;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduletasks;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Service;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicegroup;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetask;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sos;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosdefaultmessageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.User;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MandantRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessageRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessageactionRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagebamRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagebammandantRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagebamtypeRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagepropertyRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagepropertysearchlistentryRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.MessagestatistichistoryRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ProcessRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ProjectRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ProjectmandantRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ScheduleRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ScheduleplansRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ScheduletasksRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServiceRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServicegroupRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServicetaskRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.ServicetypeRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.SosRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.SosactionRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.SosdefaultmessagepropertyRecord;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.records.UserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * GlassfishDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MandantRecord> KEY_MANDANT_PRIMARY = Internal.createUniqueKey(Mandant.MANDANT, DSL.name("KEY_Mandant_PRIMARY"), new TableField[] { Mandant.MANDANT.MANDANTID }, true);
    public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = Internal.createUniqueKey(Message.MESSAGE, DSL.name("KEY_Message_PRIMARY"), new TableField[] { Message.MESSAGE.MESSAGEID }, true);
    public static final UniqueKey<MessageactionRecord> KEY_MESSAGEACTION_PRIMARY = Internal.createUniqueKey(Messageaction.MESSAGEACTION, DSL.name("KEY_MessageAction_PRIMARY"), new TableField[] { Messageaction.MESSAGEACTION.MESSAGEID, Messageaction.MESSAGEACTION.MESSAGEACTIONID }, true);
    public static final UniqueKey<MessagebamRecord> KEY_MESSAGEBAM_PRIMARY = Internal.createUniqueKey(Messagebam.MESSAGEBAM, DSL.name("KEY_MessageBAM_PRIMARY"), new TableField[] { Messagebam.MESSAGEBAM.MESSAGEID, Messagebam.MESSAGEBAM.MESSAGEBAMTYPE, Messagebam.MESSAGEBAM.MESSAGEBAMVALUE }, true);
    public static final UniqueKey<MessagebammandantRecord> KEY_MESSAGEBAMMANDANT_PRIMARY = Internal.createUniqueKey(Messagebammandant.MESSAGEBAMMANDANT, DSL.name("KEY_MessageBAMMandant_PRIMARY"), new TableField[] { Messagebammandant.MESSAGEBAMMANDANT.MESSAGEBAMTYPE, Messagebammandant.MESSAGEBAMMANDANT.MANDANTID }, true);
    public static final UniqueKey<MessagebamtypeRecord> KEY_MESSAGEBAMTYPE_PRIMARY = Internal.createUniqueKey(Messagebamtype.MESSAGEBAMTYPE, DSL.name("KEY_MessageBAMType_PRIMARY"), new TableField[] { Messagebamtype.MESSAGEBAMTYPE.MESSAGEBAMTYPE_ }, true);
    public static final UniqueKey<MessagepropertyRecord> KEY_MESSAGEPROPERTY_PRIMARY = Internal.createUniqueKey(Messageproperty.MESSAGEPROPERTY, DSL.name("KEY_MessageProperty_PRIMARY"), new TableField[] { Messageproperty.MESSAGEPROPERTY.MESSAGEID, Messageproperty.MESSAGEPROPERTY.MESSAGEPROPERTYNAME, Messageproperty.MESSAGEPROPERTY.MESSAGEACTIONID }, true);
    public static final UniqueKey<MessagepropertysearchlistentryRecord> KEY_MESSAGEPROPERTYSEARCHLISTENTRY_PRIMARY = Internal.createUniqueKey(Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY, DSL.name("KEY_MessagePropertySearchListEntry_PRIMARY"), new TableField[] { Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY.MESSAGEPROPERTYNAME }, true);
    public static final UniqueKey<MessagestatistichistoryRecord> KEY_MESSAGESTATISTICHISTORY_PRIMARY = Internal.createUniqueKey(Messagestatistichistory.MESSAGESTATISTICHISTORY, DSL.name("KEY_MessageStatisticHistory_PRIMARY"), new TableField[] { Messagestatistichistory.MESSAGESTATISTICHISTORY.PERIOD }, true);
    public static final UniqueKey<ProcessRecord> KEY_PROCESS_PRIMARY = Internal.createUniqueKey(Process.PROCESS, DSL.name("KEY_Process_PRIMARY"), new TableField[] { Process.PROCESS.PROCESSID }, true);
    public static final UniqueKey<ProjectRecord> KEY_PROJECT_PRIMARY = Internal.createUniqueKey(Project.PROJECT, DSL.name("KEY_Project_PRIMARY"), new TableField[] { Project.PROJECT.PROJECTID }, true);
    public static final UniqueKey<ProjectmandantRecord> KEY_PROJECTMANDANT_PRIMARY = Internal.createUniqueKey(Projectmandant.PROJECTMANDANT, DSL.name("KEY_ProjectMandant_PRIMARY"), new TableField[] { Projectmandant.PROJECTMANDANT.PROJECTID, Projectmandant.PROJECTMANDANT.MANDANTID }, true);
    public static final UniqueKey<ScheduleRecord> KEY_SCHEDULE_PRIMARY = Internal.createUniqueKey(Schedule.SCHEDULE, DSL.name("KEY_Schedule_PRIMARY"), new TableField[] { Schedule.SCHEDULE.SCHEDULEID }, true);
    public static final UniqueKey<ScheduleplansRecord> KEY_SCHEDULEPLANS_PRIMARY = Internal.createUniqueKey(Scheduleplans.SCHEDULEPLANS, DSL.name("KEY_SchedulePlans_PRIMARY"), new TableField[] { Scheduleplans.SCHEDULEPLANS.SCHEDULEID, Scheduleplans.SCHEDULEPLANS.ACTIONID }, true);
    public static final UniqueKey<ScheduletasksRecord> KEY_SCHEDULETASKS_PRIMARY = Internal.createUniqueKey(Scheduletasks.SCHEDULETASKS, DSL.name("KEY_ScheduleTasks_PRIMARY"), new TableField[] { Scheduletasks.SCHEDULETASKS.ACTIONID, Scheduletasks.SCHEDULETASKS.EXECUTION }, true);
    public static final UniqueKey<ServiceRecord> KEY_SERVICE_PRIMARY = Internal.createUniqueKey(Service.SERVICE, DSL.name("KEY_Service_PRIMARY"), new TableField[] { Service.SERVICE.SERVICEID }, true);
    public static final UniqueKey<ServicegroupRecord> KEY_SERVICEGROUP_PRIMARY = Internal.createUniqueKey(Servicegroup.SERVICEGROUP, DSL.name("KEY_ServiceGroup_PRIMARY"), new TableField[] { Servicegroup.SERVICEGROUP.SERVICEGROUPID }, true);
    public static final UniqueKey<ServicetaskRecord> KEY_SERVICETASK_PRIMARY = Internal.createUniqueKey(Servicetask.SERVICETASK, DSL.name("KEY_ServiceTask_PRIMARY"), new TableField[] { Servicetask.SERVICETASK.SERVICETASKID, Servicetask.SERVICETASK.SERVICEID }, true);
    public static final UniqueKey<ServicetypeRecord> KEY_SERVICETYPE_PRIMARY = Internal.createUniqueKey(Servicetype.SERVICETYPE, DSL.name("KEY_ServiceType_PRIMARY"), new TableField[] { Servicetype.SERVICETYPE.SERVICETYPEID }, true);
    public static final UniqueKey<SosRecord> KEY_SOS_PRIMARY = Internal.createUniqueKey(Sos.SOS, DSL.name("KEY_SOS_PRIMARY"), new TableField[] { Sos.SOS.SOSID }, true);
    public static final UniqueKey<SosactionRecord> KEY_SOSACTION_PRIMARY = Internal.createUniqueKey(Sosaction.SOSACTION, DSL.name("KEY_SOSAction_PRIMARY"), new TableField[] { Sosaction.SOSACTION.SOSID, Sosaction.SOSACTION.SOSACTIONID }, true);
    public static final UniqueKey<SosdefaultmessagepropertyRecord> KEY_SOSDEFAULTMESSAGEPROPERTY_PRIMARY = Internal.createUniqueKey(Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY, DSL.name("KEY_SOSDefaultMessageProperty_PRIMARY"), new TableField[] { Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY.SOSID, Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY.MESSAGEPROPERTYNAME }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_User_PRIMARY"), new TableField[] { User.USER.USERID }, true);
}
