/*
 * This file is generated by jOOQ.
 */
package de.kraftwerkone.overlord.monitor.jooq.glassfish;


import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Mandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Message;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebam;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebammandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagebamtype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagemandantid;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagepropertysearchlistentry;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistic;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Messagestatistichistory;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Process;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Project;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Projectmandant;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Schedule;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduleplans;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Scheduletasks;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Service;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicegroup;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetask;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Servicetype;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sos;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosaction;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.Sosdefaultmessageproperty;
import de.kraftwerkone.overlord.monitor.jooq.glassfish.tables.User;


/**
 * Convenience access to all tables in GlassfishDB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>GlassfishDB.Mandant</code>.
     */
    public static final Mandant MANDANT = Mandant.MANDANT;

    /**
     * The table <code>GlassfishDB.Message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>GlassfishDB.MessageAction</code>.
     */
    public static final Messageaction MESSAGEACTION = Messageaction.MESSAGEACTION;

    /**
     * The table <code>GlassfishDB.MessageBAM</code>.
     */
    public static final Messagebam MESSAGEBAM = Messagebam.MESSAGEBAM;

    /**
     * The table <code>GlassfishDB.MessageBAMMandant</code>.
     */
    public static final Messagebammandant MESSAGEBAMMANDANT = Messagebammandant.MESSAGEBAMMANDANT;

    /**
     * The table <code>GlassfishDB.MessageBAMType</code>.
     */
    public static final Messagebamtype MESSAGEBAMTYPE = Messagebamtype.MESSAGEBAMTYPE;

    /**
     * The table <code>GlassfishDB.MessageMandantID</code>.
     */
    public static final Messagemandantid MESSAGEMANDANTID = Messagemandantid.MESSAGEMANDANTID;

    /**
     * The table <code>GlassfishDB.MessageProperty</code>.
     */
    public static final Messageproperty MESSAGEPROPERTY = Messageproperty.MESSAGEPROPERTY;

    /**
     * The table <code>GlassfishDB.MessagePropertySearchListEntry</code>.
     */
    public static final Messagepropertysearchlistentry MESSAGEPROPERTYSEARCHLISTENTRY = Messagepropertysearchlistentry.MESSAGEPROPERTYSEARCHLISTENTRY;

    /**
     * The table <code>GlassfishDB.MessageStatistic</code>.
     */
    public static final Messagestatistic MESSAGESTATISTIC = Messagestatistic.MESSAGESTATISTIC;

    /**
     * The table <code>GlassfishDB.MessageStatisticHistory</code>.
     */
    public static final Messagestatistichistory MESSAGESTATISTICHISTORY = Messagestatistichistory.MESSAGESTATISTICHISTORY;

    /**
     * The table <code>GlassfishDB.Process</code>.
     */
    public static final Process PROCESS = Process.PROCESS;

    /**
     * The table <code>GlassfishDB.Project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>GlassfishDB.ProjectMandant</code>.
     */
    public static final Projectmandant PROJECTMANDANT = Projectmandant.PROJECTMANDANT;

    /**
     * The table <code>GlassfishDB.Schedule</code>.
     */
    public static final Schedule SCHEDULE = Schedule.SCHEDULE;

    /**
     * The table <code>GlassfishDB.SchedulePlans</code>.
     */
    public static final Scheduleplans SCHEDULEPLANS = Scheduleplans.SCHEDULEPLANS;

    /**
     * The table <code>GlassfishDB.ScheduleTasks</code>.
     */
    public static final Scheduletasks SCHEDULETASKS = Scheduletasks.SCHEDULETASKS;

    /**
     * The table <code>GlassfishDB.Service</code>.
     */
    public static final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>GlassfishDB.ServiceGroup</code>.
     */
    public static final Servicegroup SERVICEGROUP = Servicegroup.SERVICEGROUP;

    /**
     * The table <code>GlassfishDB.ServiceTask</code>.
     */
    public static final Servicetask SERVICETASK = Servicetask.SERVICETASK;

    /**
     * The table <code>GlassfishDB.ServiceType</code>.
     */
    public static final Servicetype SERVICETYPE = Servicetype.SERVICETYPE;

    /**
     * Sequence of Services
     */
    public static final Sos SOS = Sos.SOS;

    /**
     * The table <code>GlassfishDB.SOSAction</code>.
     */
    public static final Sosaction SOSACTION = Sosaction.SOSACTION;

    /**
     * The table <code>GlassfishDB.SOSDefaultMessageProperty</code>.
     */
    public static final Sosdefaultmessageproperty SOSDEFAULTMESSAGEPROPERTY = Sosdefaultmessageproperty.SOSDEFAULTMESSAGEPROPERTY;

    /**
     * The table <code>GlassfishDB.User</code>.
     */
    public static final User USER = User.USER;
}
